### ISSUE TITLE
[Feature Request] Add enable/disable viewport/rendering settings to FLIP Fluid button

### ISSUE THREAD

**Issue by GuyJan** [rlguy/Blender-FLIP-Fluids#222]
![image](https://user-images.githubusercontent.com/15571136/37905883-9cf5a994-3100-11e8-884b-8ef82e3bbc02.png)
Is it possible to enable/disable flip fluid like for instance physics for "smoke", (without resetting the bake) ?

**Comment by Mitsuma** [comment]
You can just hide the parts you don't want inside the domain object.
![blender_2018-03-26_15-18-37](https://user-images.githubusercontent.com/8568089/37908613-098493b0-3109-11e8-904e-9c768b18ddc1.png)

**Comment by GuyJan** [comment]
With Flip fluid is only part of my project, and when this part is not visible, I should like to disable FF, while it slows down drastically my  animation.

When baked, my animation runs at 0.6 fps.

Hiding the objects inside the domain doesn’t change this speed. After resetting the bake, the speed increases to 3-4 fps, but I have to rebake each time when necessary, which is also time consuming.



 

A workaround is to delete the current cache directory:



 

Then the speed restores to 3-4 fps. 

When necessary, i restore the path in the current cache directory, and I return tot he first image.

 

Maybe there is a more elegant way?

Br,

Guy

**Comment by rlguy** [comment]
I'll add those render/viewport enable/disable controls so that the FLIP Fluid physics button is consistent with how the internal Fluid button works.

For now, you can set the viewport diplay setting to 'None' so that the addon does not load meshes into the viewport:

![viewport_display_none](https://user-images.githubusercontent.com/4285191/37931084-64db20d6-30f9-11e8-8f97-ec4fce8a5fc7.jpg)

Or you can use the 'Quick Viewport Settings' in the toolbox menu to quickly set the viewport settings to 'None':

![viewport_toolbox_none](https://user-images.githubusercontent.com/4285191/37931085-64ef75ae-30f9-11e8-8b0c-6d4df86d35d5.jpg)

**Comment by rlguy** [comment]
This has been added and will be included in the next version update (**1.0.4**).

![display_settings](https://user-images.githubusercontent.com/4285191/41207207-5bfbf540-6cc6-11e8-9e4a-a24d3e73ebd7.jpg)
