### ISSUE TITLE
Interaction of objects with the fluid.

### ISSUE THREAD

**Issue by liell** [rlguy/Blender-FLIP-Fluids#293]
When I simulate some object with the physics of Blender, I would like it to interact with the fluid when it falls.
The problem is that it bakes before the fluid is created, hence its motion is already established without the fluid and then it just repeats the bake's motion.
Is it possible to do with what the bake of the object is done together with the generation of the fluid and that when it comes into contact with the fluid it respects the physics of the fluid?
To be able to do something like that.

In the 11 seconds of the video has the example.
https://vimeo.com/252313372

Thank you very much.

**Comment by liell** [comment]
I got to do a test, but I did, animating the strawberry manually to make it look like it fell into the fluid.
![iogurte_wip_01](https://user-images.githubusercontent.com/6620715/39816037-5fcc7164-5370-11e8-85ea-d3dc572ebdf2.gif)

**Comment by rlguy** [comment]
Hey liell,

Animation looks great!

Unfortunately, the fluid simulator is not able to affect the motion of rigid body objects. Obstacle objects can push around the fluid, but fluid is not able to push around obstacles. This is because there is not a way to communicate fluid forces with Blender's rigid body simulator.
