### ISSUE TITLE
OctaneRender: Set meshtype to "global".

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#300]
This is for Octane users. To be able to render fluid surfaces as animation its requiered to set the meshtype of the surface to "global".
Could the addon detect when Octane is used and set the meshtype automaticly?

https://i.imgur.com/GWmWEZA.png

**Comment by dafassi** [comment]
Fantastic!
You can call it with: bpy.context.object.data.octane.mesh_type = '0'

**Comment by rlguy** [comment]
This was added long ago! Forgot to close this issue.

**Comment by richardklingler** [comment]
Could it be that this is not available on the demo version of the plugin?

**Comment by rlguy** [comment]
Hi richardklingler,

I just had a chance to check this out. It turns out the demo example scenes will not automatically set the mesh type to 'Global'. For this functionality, scenes/simulations will need to be created within the Octane Blender plugin. Since the demo scenes were created in regular Blender, the fluid mesh objects will not have these octane settings automatically set.

For the demo scenes, you will need to set the Octane Mesh Type manually:

![mesh_type_global](https://user-images.githubusercontent.com/4285191/48437597-993d9400-e736-11e8-9ff5-04b90b2e9300.jpg)

Alternatively, you may delete the 'fluid_surface' object and reload a frame. This will re-build the fluid surface object and the demo addon should detect Octane and apply the mesh type setting.

\- Ryan
