### ISSUE TITLE
[Feature Request] Fluid Interaction with Rigid Bodies

### ISSUE THREAD

**Issue by donalffons** [rlguy/Blender-FLIP-Fluids#303]
Thanks for this great Addon!

One thing that I would find very useful would be to simulate rigid bodies being affected by fluids. For example, currently it's not possible to simulate boxes floating on water or a wave crashing into some obstacle and destroying it. Correct me if I am wrong :).

Best regards
-Sebastian

**Comment by rlguy** [comment]
Unfortunately this will not be possible in Blender.

From the product page FAQ:

> **Can the fluid simulation push around rigid body objects?**
The fluid simulator is not able to affect the motion of rigid body objects. Obstacle objects can push around the fluid, but fluid is not able to push around obstacles. This is because there is not a way to communicate fluid forces with Blender's rigid body simulator.

**Comment by k1ff** [comment]
Blender seriously needs to consider re writing their ridged body simulator then as a lot of people have been asking for this feature for the Flip Fluids addon. Would this be possible in the Fracture branch of Blender? Or would Blender itself need new a new way of computing RBD?
