### ISSUE TITLE
Obstacle ignored

### ISSUE THREAD

**Issue by rfosdal** [rlguy/Blender-FLIP-Fluids#304]
I have been playing around with the add-on for a few days. One thing gives me a huge problem. If I create a sphere and remove the top - that gives me a bowl. The normals are a mess so I apply a solidifier and check the normals. Everything looks good. 
I add an inflow cylinder above the center of the bowl and a fluid domain surrounding the whole thing.
It all looks good. Until I start baking. The fluid runs straight through. I tried turning the bow up-side down, same result. The geometry looks to be ok and closed.

I use the same object with the internal Blender FS and it works as expected. What am I doing wrong? Or is this a bug?

I have attached a couple of screenshots and the .blend file. Needless to say this is driving me nuts lol

Best regards

Rene Fosdal-Griffin
[WaterBowl.blend.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2009248/WaterBowl.blend.zip)
![fluid domain](https://user-images.githubusercontent.com/17729512/40119035-81f90664-5913-11e8-8784-fa4eab855c3f.JPG)
![inflow_obstacle](https://user-images.githubusercontent.com/17729512/40119036-82147d90-5913-11e8-96c6-f9a322e5a9e4.JPG)
![inflow_obstacle2](https://user-images.githubusercontent.com/17729512/40119037-822dcf7a-5913-11e8-800c-4e64a3b4bf4a.JPG)
![inflow](https://user-images.githubusercontent.com/17729512/40119038-82477128-5913-11e8-89dc-f0cdcc999e45.JPG)
![obstacle](https://user-images.githubusercontent.com/17729512/40119039-82614f6c-5913-11e8-807b-fb6a4389baaf.JPG)

**Comment by rlguy** [comment]
Hello rfosdal,

This is caused by the use of a thin obstacle in a relatively low resolution domain. Simulation calculations are made on a grid, and if the grid is not detailed enough (low resolution), the object may not show up effectively on the grid for collision calculation.

Check out this comment for how to handle simulations with thin obstacles:
https://github.com/rlguy/Blender-FLIP-Fluids/issues/148#issuecomment-368624558

And just a note, obstacle objects must be [Manifold](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes), but it seems like you fixed this by adding the solidify modifier.

Hope this helps!

**Comment by rfosdal** [comment]
Thanks for the feedback - I had already had a look at the other post but nothing seemed to change the simulation outcome. 
However, it seems that make the half-sphere followed by duplicate and scaling (and obviously bridging the edge loops) gave a much better result compared to using the solidifier.

The add-on is great it's fairly stable (I find that I have to finish the simulation and then close Blender before rendering an animation). On the Mac I have some crashes but they seem random at the moment. I will document that later when I have the time.

Cheers,

Rene
