### ISSUE TITLE
Multithreading / GPU usage, and related questions.

### ISSUE THREAD

**Issue by philstopford** [rlguy/Blender-FLIP-Fluids#306]
I'm running a 64 GB i7 6700K with a 6 GB GTX 1060. I don't see any evident sustained GPU usage reported by the Windows 10 task manager, and the CPU activity is quite uneven. So, I'm curious about a number of things : 

1) How does the blender memory size related to the fluid related memory and potential need for free memory on the GPU?
2) Is it expected that the CPU usage varies so strongly during a simulation run (I'm seeing swings between 20% and 75% on the lighthouse scene, with 9 GB memory usage reported by blender)
3) I see some very occasional GPU activity (5% or so).

The docs don't seem to go into great detail about what to expect here, but if I missed something, I apologize for the noise.

Thanks for a great, and very affordable, addon.

**Comment by rlguy** [comment]
Hey philstopford,

This is all normal and expected of the simulator. For CPU usage, the short answer is that the simulation is just a series of different calculations run one after the other. Some calculations can be multithreaded effectively (high CPU usage), some calculations are not able to be multithreaded (single core, low CPU usage). So that is why you will see swings of CPU usage. GPU memory usage during simulation will be quite low compared to how much Blender requires.

Check out these links for more detailed info:
https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-cpu-is-running-under-100-usage-while-simulating-is-this-normal

https://github.com/rlguy/Blender-FLIP-Fluids-Beta/wiki/Frequently-Asked-Questions#my-gpu-usage-is-very-low-is-this-normal

The _Frequently Asked Questions_ page was written for the Beta, is a bit out of date, and not easy to find so don't worry about missing it! I'll need to update the page and link it in with the documentation.

Great to hear that you're enjoying the addon!
