### ISSUE TITLE
Flip fluids is going through the objects with collision

### ISSUE THREAD

**Issue by EmigeDaniel** [rlguy/Blender-FLIP-Fluids#307]
Even if I have left the resolution high, the fluid remains going through the same objects always. I don't know how I can solve it!
![flipfb](https://user-images.githubusercontent.com/39391046/40210036-307c2f9e-5a19-11e8-9ebc-b9facf39911e.gif)

**Comment by rlguy** [comment]
Hey,

Would you be able to attach the scene for me to check out and test? You will need to create a .zip of the .blend file to attach the file to this issue. Alternatively, you may send the file to flip.fluids.beta@gmail.com.

I’ll be able to take a look at this within the next few hours.

**Comment by EmigeDaniel** [comment]
Ok!

**Comment by rlguy** [comment]
Hey EmigeDaniel,

Thanks for sending your scene, I just took a look! The problem is that your obstacle mesh is [non-manifold](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes). The simulator requires objects to be manifold and is noted in the [Obstacle Documentation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings). This is so that calculations can be made for what parts of the mesh are _inside_ and what parts are _outside_. Non-manifold meshes do not have a clearly defined inside and outside so results can be unexpected in the simulator.

Tip: you can highlight non manifold edges/vertices in _Edit Mode_ and using the _**ctrl+alt+shit+m**_ command.

![non_manifold](https://user-images.githubusercontent.com/4285191/40213593-17292870-5a0b-11e8-864a-6c86e0870c85.jpg)

There are many ways to fix non-manifold meshes through manual modelling. There is also a built-in addon called _**3D Print Toolbox**_ (you will need to enable in your user settings) that will automatically make your mesh manifold by adding edges/faces but the results can be undesirable depending on the starting mesh. Here is the fluid interacting with your obstacle after making it manifold:

![manifold](https://user-images.githubusercontent.com/4285191/40213676-8ceef0f8-5a0b-11e8-8688-c7ed4c95b91f.jpg)

Hope this helps and clears up the issue for you!

**Comment by EmigeDaniel** [comment]
Thanks, I added the modifier solidify and solved the problem!!
