### ISSUE TITLE
Preset manager duplicates materials

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#321]
While editing the presets i found out, that duplicates of used materials will be created.
https://i.imgur.com/AhazDwK.png

**Comment by rlguy** [comment]
Hey, this is a side effect of editing presets with materials and is unfortunately unavoidable. This occurs because the addon needs to import materials from a separate .blend file. The addon is not able to detect if two materials are identical, so it will end up copying and making duplicates if a material with the same name is present in the main .blend file.
