### ISSUE TITLE
[Feature Request][Requires Documentation] Allow inflow objects to continue filling when 'under water'

### ISSUE THREAD

**Issue by Corefrecs** [rlguy/Blender-FLIP-Fluids#322]
Hey RLGuy,
I’m trying to fill a tube from bottom to the top but it always stops filling when the water reaches the highest part of the inflow object (a sphere). 
Can it be that the inflow object only creates new particles when there aren’t any within this object (like when they fall down because of the gravity)? Or better sayd: the inflow object does not create a pressure that pushes the existing particles away? 

Hope you know what I mean and that there is a work around for this.
Cheers

**Comment by rlguy** [comment]
Hey Corefrecs,

In the simulator, inflow objects will only create particles where there is empty space and that is why they will stop filling the domain when the inflow is covered by particles. At the moment there is no workaround for this, unfortunately. I'll need to think of a way to get the inflow objects to create a pressure on the surrounding fluid so that it can continuously emit particles. I have some ideas, just need to find some time and try them out!

Note: I believe fixing this issue will also solve these issues as a side effect: #90, #271

- Ryan

**Comment by Corefrecs** [comment]
Ok thanks for clearing this up! I’ll try a workaround like zero-g or a U-form Tube to fill it.

**Comment by rlguy** [comment]
This ended up being quite an interesting problem to solve!

An option to force fluid inside of an inflow object to match the emission velocity of the inflow has been added. This option will be included in the next version update (**1.0.4**). This option will allow inflows to continue emitting when submerged with some scene modifications.

![constrain_inflow](https://user-images.githubusercontent.com/4285191/41320968-b2545ebe-6e56-11e8-998a-f5996837eb02.jpg)

Documentation should be added for how to create a scene where a submerged inflow fills up a domain.

### Documentation Notes

Enabling the 'Constrain Fluid Velocity' option will allow an inflow to push around fluid when submerged. An inflow by itself will not be able to create new fluid and continue filling a domain when submerged, however. This is due to a physical limitation. Inflows that spawn fluid out of nowhere do not exist in real life. Due to this physical limitation, a submerged inflow is not able to exert a velocity pressure on the surrounding fluid in a way that creates a displacement so that more fluid can be created to fill up the domain. All the inflow can do is push around and circulate the fluid within the tank.

In real life, a tank would be filled using a pipe where the fluid is sourced elsewhere and perhaps uses a machine to 'pump' the liquid into the tank. To create a scenario within the simulator where an inflow can fill up a tank, a pipe obstacle object will need to be created with an inflow located inside of the pipe object. The inflow velocity setting will act as the 'pump' that pushes fluid through the pipe and fills up the tank.

![pipe_inflow](https://user-images.githubusercontent.com/4285191/41321511-288ed684-6e59-11e8-9e75-3c05aa1fc377.jpg)

Using this pipe setup, the inflow is now able to push out fluid and fill up the tank, even when submerged. The pipe object that surrounds the inflow prevents outside fluid from entering the inflow object and being recirculated. 

Here is an animation of the pipe setup: [inflow pipe](https://gfycat.com/ScaredPepperyAplomadofalcon)

And here is an animation with just the inflow (no pipe): [inflow no pipe](https://gfycat.com/EuphoricMedicalBarasinga)

**Comment by Corefrecs** [comment]
Great to hear that you found a solution! this looks very promissing and by doing this scene modification, the simulation would automaticly look more realistic ;)

Can't wait for the 1.0.4  Update, seams like every feature I'm missing right now will be includet! :)

**Comment by rlguy** [comment]
Version **1.0.4** is coming soon (August 11th), so I have just added documentation for how to use this feature.

Documentation Links:
- Parameter Documentation (_Constrain Fluid Velocity_): https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Object-Settings#parameters
- Additional notes and applications of this setting: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Constrain-Fluid-Velocity-Additional-Notes
- And since filling up a tank is a common request, I have added a scene troubleshooting topic here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#inflow-will-not-fill-up-a-tank-when-submerged
