### ISSUE TITLE
Emitted fluid vanishes mid-air in tiny domain

### ISSUE THREAD

**Issue by ArrowheadVenom** [rlguy/Blender-FLIP-Fluids#337]
I'll just link my .blend: http://pasteall.org/blend/index.php?id=49725 (And I just realized the target for the inflow velocity needs to be re-chosen since I renamed the Empty to "target".)

I've turned on World Scaling and set the domain size to just 0.1 meters. Very small, but accurate if I want this to be a rather small cup. Actually it's still probably too large anyway.
If you bake it, you should see the fluid start to spray downward as intended, but just sort of stops and vanishes before descending into the cup. Also, no whitewater particles are being generated, but that's a separate issue I guess. I'm using the beer preset just to try and test the whitewater.

Any idea what's up? Thanks.

**Comment by rlguy** [comment]
Hey ArrowheadVenom,

The disappearing fluid issue can be resolved by increasing the increasing the **Max Frame Substeps** value in the [Advanced Panel](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Advanced-Settings#frame-substeps). Try setting this to a high value such as 50. This is a common issue, so I have just added an explanation for this here: [Scene Troubleshooting: Fast moving fluid disappears from simulation](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#fast-moving-fluid-disappears-from-simulation).

As for no whitewater particles being generated, this section may help explain this: [Scene Troubleshooting: Simulation not generating enough whitewater (foam/bubble/spray)](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#simulation-not-generating-enough-whitewater-foambubblespray). **Tip number 4** will be relevant since you are using a small domain.

And also, since you are using a small domain, you may want to read this which explains issues with small world sizes: [Scene Troubleshooting: Difficulty achieving small scale fluid effects with small World Size](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#difficulty-achieving-small-scale-fluid-effects-with-small-world-size).

Hope this helps!

\- Ryan

**Comment by ArrowheadVenom** [comment]
Thanks so much! Very helpful.
