### ISSUE TITLE
Whitewater particle scale in viewport does not update when frame is reloaded

### ISSUE THREAD

**Issue by Edrift3d** [rlguy/Blender-FLIP-Fluids#339]
I'm following the Magical Scene tutorial on YouTube and I'm trying to scale the whitewater foam, bubble etc to fit my scene. Apparently it is only changing the scale of the particles the first time the scale is changed in the viewport.

1. I uncheck Render only box and then change the scale of the particles and reload the frame either by the reload frame button in the tool panel or toggling a frame in the timeline. Works fine.
2. I change the scale again in the Flip Display settings and reload the frame and nothing happens.

Only way I've gotten around this is to reload the scene with the bake BEFORE I changed the scale. Once you change the scale and save the scene and reopen it, it's stuck at the new scale in the viewport.

This also appears to be a viewport only issue. I can still do a full offline render and the scale with change correctly even though the viewport doesn't match.

Blender 2.79b
Windows 10

**Comment by rlguy** [comment]
Hey Edrift3d,

Thank you for reporting this! It looks like this bug is a side effect of changes made during the last version update.

Until this is fixed, there is a workaround to reload the particles and update the viewport particle size: change the **Final Whitewater Percent** value (or preview whitewater percent if viewport display mode is set to preview) and then reload the frame.

![particle_display_settings](https://user-images.githubusercontent.com/4285191/41556932-f757fbf8-72f0-11e8-946e-89ddc5ca479e.jpg)

\- Ryan

**Comment by rlguy** [comment]
This has been fixed and will be included in the next version update (**1.0.4 available August 11th**).
