### ISSUE TITLE
'Cannot find fluid engine library: pyfluid.dll'

### ISSUE THREAD

**Issue by plantjeee** [rlguy/Blender-FLIP-Fluids#343]
Hi,

So i've been trying to figure out how to get this addon to work for the past 2 days.

Every time i try to bake a simulation i get the following error message:
"Cannot find fluid engine library :pyfluid.dll"

Now this is a compiled build from your git, at first it would show that it was looking for a libpyfluid.dll, but after browsing through your github page i've found out it's supposed to be pyfluid.dll.

But alas still no fix.
I noticed you recommended to a few people to reinstall their GPU drivers but after doing this twice the issue is still not resolved.

I've browsed through the files to look for the .dll myself but i can't seem to find that either.

I've also noticed that when i press the search for GPU devices button in the user pref. menu i get the following screen

![errorlog2](https://user-images.githubusercontent.com/31519549/41670218-fdaf3df8-74b3-11e8-809e-39600a87639b.png)

Is this an issue with my build or am i doing something horribly wrong?

[errorlog.txt](https://github.com/rlguy/Blender-FLIP-Fluids/files/2120119/errorlog.txt)

Thank you in advance!

**Comment by rlguy** [comment]
Hello plantjeee,

It sounds like the library may not be building correctly. This could be caused by a difference in build systems between your machine and our build machine. I am sorry to say that we currently do not have resources to offer build support for for this repository. We actually can only offer support for the Blender Market product at the moment.
