### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by GuyJan** [rlguy/Blender-FLIP-Fluids#353]
I am simulating a vintage industrial installation (Newcomen steam engine), consisting of a domain with 3 independent reservoirs (one has animated dimensions), at different positions, each with one or 2 inflows and one outflow. The dimensions x, y, z in meters are:
- domain: 12x10x15 -determined by the relative positions of the reservoirs

-position 1; reservoir size: 9x1x1, inflow size 0.7x0.7x1 and 0.3x0.3x0..1

-position 2: reservoir size: 3x3x1, inflow size 0.5x0.5x0.1

- position 3: reservoir size; 2x2x(0.1-3 animated), inflow 0.05x0.05x0.05
I had to increase the resolution to  600 to obtain an acceptable result (fluid cell dimension 2.6mm ??). At a resolution of 200 there was even no fluid coming out of the inflow of position 3 - to few cells?.

This results in a huge cache file (> 8 GB) and a baking time of > 30 hours.

Could it be possible to have separate domains with smaller dimensions and approriated resolutions, each with its own cache?
Guy

**Comment by rlguy** [comment]
Hey GuyJan,

A limitation of the addon is that only one domain can exist in a single scene. This is due to how the addon was designed early on in development. Unfortunately, this design is integrated so deeply into the addon that it is unlikely that multiple domains will be supported in the future since it would require a large re-write of the code.

However, it might be possible to add a feature to import multiple simulation caches into a single scene. You would still need to bake simulations in separate .blend files, but this feature would allow you to playback/render multiple simulations in a single scene. This feature would be much more manageable to add than it would be to add support for multiple fully-functional domains within a scene. Would this type of feature be useful for your situation?

A workaround I have seen another user use to import multiple simulations in a single scene is to export a simulation to Alembic cache and then import the cache into another scene for playback/rendering. There is a method to export to Alembic cache here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#export-to-alembic-cache-is-not-exporting-animated-meshes

\- Ryan

**Comment by GuyJan** [comment]
Hallo Ryan,

Thanks fort his useful info.

I splitted the scene over 3 different blend files, each with its own  reduced domain, and will try to arrange things during video editing.

You mentioned a feature to import multiple simulation caches into a single scene. This will be very useful, and more elegant than what I am doing now. Will each cache be allowed to have its own settings like resolution etc.?

Br,

Guy

**Comment by rlguy** [comment]
I have added a feature request to import multiple simulation caches into a single scene here: #355. Each cache will be baked in a separate scene, so they will have all their settings such as resolution already baked into the meshes. Each imported cache will have separate settings for playback and rendering ([Display Settings](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Display-Settings) and [Material Settings](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Material-Settings) panels).

**Comment by GuyJan** [comment]
Sounds perfect – thanks.

Guy
