### ISSUE TITLE
Foam/bubbles/spray dont render or stay static when rendering animation

### ISSUE THREAD

**Issue by NovioK** [rlguy/Blender-FLIP-Fluids#359]
I left a sim rendering or night only to find that the foam particles at some point either disappear or stay static.  If i scrub through my timeline, everything is fine and If I render individual frames, everything renders correctly.  This happens only when I set to render an animation.

**Comment by NovioK** [comment]
actually, this alos happens on some individual frames too

**Comment by NovioK** [comment]
The only way I can it to render properly is to shut down blender and reopen the scene, render one frame, then shut down blender again and reopen to render each following frame.
It seems as though the foam/spray/bubbles are not loaded when trying to render more than one frame.

**Comment by rlguy** [comment]
Hello Noviok,

Please read our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) and [Guidelines For Reporting Bugs/Issues](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues) documents.

Attaching a scene where you are experiencing this issue would help us towards finding why this issue is occurring. Please also list your system and software information.

I am not sure if this is related, but does this render issue workaround fix the issue for you? [Scene Troubleshooting: Blender often crashes suddenly or does not apply transforms while rendering](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#blender-often-crashes-suddenly-or-does-not-apply-transforms-while-rendering).

Thanks,
Ryan

**Comment by NovioK** [comment]
Thanks for getting back to me Ryan,
Your suggestion worked.  I switched the Display setting to full screen and the animation render so far has been flawless.  All particles and mesh are now loaded onto every frame being rendered.
Please let me know if you would still want my scene uploaded to you for your testing.
Really appreciate the quick and helpful feedback.
Great Add on

**Comment by rlguy** [comment]
Thanks for the update! Glad to hear that the workaround fixes the issue.

\- Ryan
