### ISSUE TITLE
Use Frame Rate doesn't update when changing blender's frame rate

### ISSUE THREAD

**Issue by lumpynose** [rlguy/Blender-FLIP-Fluids#370]
#### System Information

Blender Version (including hash): 2.79 f4dc9f9d68b
FLIP Fluids Version: 1.03
Operating System: windows 10
CPU: intel
GFX: gtx 1070
RAM: 32gb

#### Describe the bug

Use Frame Rate in the domain settings doesn't update if you change the frame rate in Blender's Render panel.

#### To Reproduce

Add a cube, set up as a domain object, change the frame rate in the Render panel.

**Comment by rlguy** [comment]
Hey lumpynose,

This is working as intended. The domain will initialize to the same frame rate as Blender, but the property is not linked so that you can set a different simulation frame rate and render frame rate. An example use case is a slow motion simulation (simulate at 120fps, render at 30fps).

\- Ryan
