### ISSUE TITLE
Small scaled simulations, dripping water

### ISSUE THREAD

**Issue by dealenki** [rlguy/Blender-FLIP-Fluids#381]
Hi, today i bought your awesome addon, i am trying generate waterdrops drips on the mesh and fall down. I cant control amount of water generate also half of the inflow mesh doesnt generate fluid at all. I duplicate mesh. One of them obstacle and one of them inflow. I cant find many documantation or tutorials. Can you check or any tips or trick, would be awesome ? 

I am using Blender2.79b 74dc9f9d68b
FlipFluid 1.0,4
Windows 10
32gb ram
Geforce GTX 1060 6GB
[test04.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2333456/test04.zip)

**Comment by rlguy** [comment]
Hello dealenki,

The inflow is not generating fluid because there is an obstacle mesh overlaid directly on top of the inflow mesh. Fluid cannot exist inside of a solid obstacle so that is why the inflow is not emitting fluid.

If you want to control the speed/amount that fluid emits from the inflow, you could use the Inflow [Constrain Fluid Velocity](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Object-Settings#parameters) option. [Additional notes on slowing inflow emission using this option here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Constrain-Fluid-Velocity-Additional-Notes#slowing-inflow-fluid-emission).

For your fluid effect of generating waterdrops that drip down the mesh, I would suggest creating smaller inflows above or on top of your obstacle object to drip fluid onto your mesh. 

And a tip: I would suggest using a lower poly model of the arm for the simulation. High poly objects can take a while for Blender to export and the simulator does not need this high detail of meshes. High detail meshes will also slow down the simulation. In general, a mesh with a few thousand polygons is usually sufficient. A common workflow in simulation is to create an object 'double', which is a low poly object for simulation and the high poly object for simulation.

As for tutorials, we have a few here: [Video Learning Series](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Video-Learning-Series). Lawrence Jaeger has also produced a nice tutorial here: https://youtu.be/3EfgsciQ5rM .

For next time, please send scene troubleshooting questions to us directly on the Blender market. Unless approved by us, this issue tracker is generally only meant for use in reporting bugs. See our [Technical Support Guidelines here]( https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines)

\- Ryan
