### ISSUE TITLE
Simulation Speed affects Fluid Behaviour

### ISSUE THREAD

**Issue by marianheinsen** [rlguy/Blender-FLIP-Fluids#386]
Blender 2.79, Flip Fluids 1.0.4
Windows 7 64bit

The Speed parameter of the domain changes how the simulation looks, not just the speed.
I rendered the same simulation with speed 1 and speed 0.1 and then played back the second one
10x faster, compared them but the two didn't match. 

Reproduce:
add a domain and a fluid object, render one version with speed 1 and a second one with speed 0.1 and 10x as many frames,
then compare the two together but play back the second simulation 10x faster.

I would expect the two simulations to behave exactly the same, as only the time should be affected.
I did not change any other parameters

example:

![speed_comparison](https://user-images.githubusercontent.com/43065575/45216315-6ee7da00-b2a0-11e8-9343-5ed6a6496441.gif)

**Comment by rlguy** [comment]
Hello marianheinsen,

Thanks for the report and the demonstration videos. This behaviour is expected and is due to how physics simulations, such as fluid, rigid body, cloth, etc, are computed.

In simulation, the physics are calculated by approximating a physics equation. Often the physics equation cannot be solved directly and the only option is to approximate the result. Physics simulations generally work by 'stepping' time by a small amount, such as the length of a frame, into the future and updating the equation with a prediction of the result. The results become more accurate when the time steps are smaller. So when you run the simulation at 1/10th of the speed you end up approximating the equation more accurately and this is why there is a difference in the simulation results.

There is a setting in the addon which will allow you to improve simulation accuracy by decreasing the length of time steps and that is the [Min Substeps](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Advanced-Settings#frame-substeps) parameter in the Advanced Settings panel. If you run the 1.0 speed simulation with a _Min Substeps_ value of 10 (1.0 / 0.1 = 10.), you should see a similar result to the 0.1 speed simulation.

Hope this explains the issue well!

\- Ryan
