### ISSUE TITLE
Particles emitted from fluid object won't cache properly or render with motion blur. 

### ISSUE THREAD

**Issue by joeyvfx** [rlguy/Blender-FLIP-Fluids#392]
#### System Information

**Blender Version (including hash): 2.79 5bd8ac9**
**FLIP Fluids Version: 1.0.4**
**Operating System: macOS 10.13.6**
**CPU: Intel i7 8700K**
**GFX: GTX 1060**
**RAM: 32GB DDR4**

#### Describe the bug

When I add a particle system to the fluid_surface object, I am unable to render proper motion blur on the particles. The particles are always blurred incorrectly. I believe this issue is also somehow tied to particle caching on the fluid_surface object, which also does not seem to work properly.

EDIT: To clarify, I am not referring to whitewater particles. 

#### To Reproduce

Open up the .blend file provided here:
[flip_particleblurproblem.blend.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2472051/flip_particleblurproblem.blend.zip)
Bake the simulation. Once it is baked, play through the scene. You can see how the particle motion looks in the viewport, with particles shooting off the fluid onto the ground. However, when rendering with motion blur on or when generating motion vectors, the particles have incorrect motion blur.

#### Expected Behaviour

The particles should blur in the proper direction at the proper length.

#### Actual Behaviour

The blur totally freaks out and makes long streaks in seemingly random directions.

#### Screenshots

Viewport rendered view, shows the positions of particles.
![screen shot 2018-10-12 at 3 07 06 am](https://user-images.githubusercontent.com/43912174/46855259-2d7fa880-cdd1-11e8-9743-9d4c3097f2c4.png)

The same frame, rendered with motion blur on. The blur doesn't look quite right!
![screen shot 2018-10-12 at 3 07 24 am](https://user-images.githubusercontent.com/43912174/46855276-32dcf300-cdd1-11e8-8aff-d2cc75553954.png)

**Comment by rlguy** [comment]
Hi joeyvfx,

Thanks for the report and the .blend file! I just had a chance to look into this issue. Unfortunately, this is an issue that cannot be fixed within this addon at the moment.

The reason for motion blur being rendered incorrectly is because the fluid_surface mesh topology is changing between frames. When mesh topology is not consistent, Blender is not able to calculate velocity or motion blur vectors correctly.

Blender does not offer functionality for addons to send velocity data into Blender so that it can be used for rendering ([current motion blur support within the addon is very limited](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Motion-Blur-Support)). We also do not have the ability to modify particle system data.

However, this may be possible in the future after the addon is updated for Blender 2.8. We are hoping that we will have more control over Blender particle systems.

\- Ryan
