### ISSUE TITLE
Baking error: "Value must be greater or equal to zero" when domain box is thin

### ISSUE THREAD

**Issue by RobbertSch** [rlguy/Blender-FLIP-Fluids#397]
#### System Information

**Blender Version (including hash) 2.79:f4dc9f9d68b**
**FLIP Fluids Version: 1.0.4**
**Operating System: Windows**
**CPU: Intel(R) Core(TM) i7-8700K CPU**
**GFX: NVIDIA GeForce GTX 1080 Ti **
**RAM: 32GB **

#### Describe the bug

When i click bake it gives me the error:
**Value must be greater than or equal to zero. See system console for error info.**

#### To Reproduce

Idk how this happened, but if you open my blend file and select the domain and hit bake then it will give this error.

#### Expected Behaviour

Just bake my sim

#### Actual Behaviour

It gives the error
**Value must be greater than or equal to zero. See system console for error info.**

#### Screenshots

![image](https://user-images.githubusercontent.com/36270511/48983068-8dfd4780-f0ea-11e8-84e8-c426cfd899f8.png)

**Comment by rlguy** [comment]
Hi RobbertSch,

Thanks for the report! It looks like the .blend file is missing. Would you be able to attach the .blend file to this issue (you will need to attach it as a .zip file)? Alternatively, you may send us the scene at **flip.fluids@gmail.com**.

This error indicates there is a bug somewhere within the settings of our addon. These types of errors are usually not too difficult for us to track down and fix.

\- Ryan

**Comment by RobbertSch** [comment]
Hi,
Just emailed the .blend file.

thank you in advance,
Robbert

**Comment by rlguy** [comment]
Hi,

Thanks for the update! I just had a chance to test the .blend file and it looks like there is a bug in the [Enable Emission Near Domain Boundary](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Whitewater-Settings#whitewater-emission-settings) setting. This bug happens when this setting is unchecked and when the domain is thin. I'll have this fixed and will include the fix in the next version or experimental version release.

Until this is fixed, there are two workarounds:
- Increase the thickness of your domain box slightly. When the domain is thick enough, this error will be bypassed.
- Or enable the **Enable Emission Near Domain Boundary** checkbox

And just a heads up: I took a look at your obstacle mesh and noticed the geometry is non-manifold. For obstacles to work correctly within the simulator, the geometry [must be manifold](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes). Non-manifold meshes could produce unexpected results within the simulator. Tip: you can highlight non-manifold geometry in Object Edit Mode with the command: **ctrl+alt+shift+m**.

\- Ryan

**Comment by RobbertSch** [comment]
It works thx! A quick question, how do you suggest making like a big ocean
without making a unrenderable project? A plane with ocean texture?

Met vriendelijk groet,

Robbert Scholten


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusvrij.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op zo 25 nov. 2018 om 22:30 schreef Ryan Guy <notifications@github.com>:

**Comment by rlguy** [comment]
We have seen users combine the simulation surface with the ocean modifier using a displacement technique. I'm not entirely sure how it works, but we're actually testing this out to find a good workflow.

Example: Tom Allen combines this [FLIP boat/wake simulation](https://www.youtube.com/watch?v=Nhxkkfijbcg) with the ocean modifier to create the illusion of an endless ocean: https://www.youtube.com/watch?v=IYbkofafILU

Artell Blender gives a brief explanation of the technique in this dolphin animation: https://www.youtube.com/watch?v=4ePy4AGf6cY

**Comment by RevDr** [comment]
If it helps, I have just posted something on this forum....
[https://blenderartists.org/t/flip-fluids-addon-a-liquid-fluid-simulation-tool-for-blender/702503/527](url)
...on his topic.

**Comment by rlguy** [comment]
This bug has been fixed and will be included in the next experimental version (9.0.5.2).
