### ISSUE TITLE
Export Fluid Data

### ISSUE THREAD

**Issue by YvHalder** [rlguy/Blender-FLIP-Fluids#411]
Hi,

I was wondering if it is possible to export flow quantities (pressures and velocities on the grid) at every timestep? I could not find anywhere how to do this or if this is even possible.

Thanks in advance.

**Comment by rlguy** [comment]
Hi YvHalder,

There is no functionality to export this kind of data in the addon. Is there a specific use case where this data would be useful to you? Is there a way that this data can be used in Blender?

\- Ryan

**Comment by rlguy** [comment]
Sounds like an interesting application! I am sorry to say that we will likely not be adding this functionality to the addon due to its limited use in Blender. We're focusing on developing features that can be used within Blender.

Are you familiar with C++ programming and compiling? If so, I would be glad to point you to areas of the code where velocity and pressure grid data can be accessed.

If you're looking for a simulation system with functionality for accessing this type of data, Houdini might be something to look into. There is a lot of customizability for what type of data to save to the cache.

**Comment by rlguy** [comment]
I will be closing this issue. If you have any further questions, feel free to comment or send us an email at flip.fluids@gmail.com.
