### ISSUE TITLE
Domain size does not go back to "normal size' after resetting a bake

### ISSUE THREAD

**Issue by semillerimages** [rlguy/Blender-FLIP-Fluids#441]
#### System Information

2,80.51 - b6d1946c2e6b-win64
v9.0.5.3 Experimental 01-FEB-2019
Win 10 Pro 64bit
Dual Xeon 2690v2
Dual 1080ti
128 GB

#### Describe the bug

The domain doesn't revert to original size when resetting the bake

#### To Reproduce

I guess you'd have to open it on your system. 

#### Expected Behaviour

Domain should go back to original size so that I can refine it.

#### Actual Behaviour

Domain stays tiny.

#### Screenshots

Screenshot attached. 
![FF-domain-problem](https://user-images.githubusercontent.com/49002786/55500411-1f327c80-55fd-11e9-9d09-8aec5437ec1a.PNG)

**Comment by rlguy** [comment]
Hi semillerimages,

Thanks for the report! I am not sure I understand what you mean by 'The domain doesn't revert to original size when resetting the bake'. Would you be able to attach a .blend file so that I could try reproducing the issue. See this document for .blend file guidelines: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues#attach-a-blend-file

Would you also be able to provide any instructions for how to use your .blend file to reproduce the issue?

\- Ryan

**Comment by semillerimages** [comment]
I think you can see here, where the domain is obviously bigger than the orange outlines of the cube. Did I do something to the scaling or? 

![FF-Domain-size](https://user-images.githubusercontent.com/49002786/55505838-dbde0b00-5608-11e9-94e7-bd53df41c026.PNG)

**Comment by rlguy** [comment]
Hi,

The fluid meshes should be contained within the domain object. If they are not, then this could be a bug within the addon. But I am not able to reproduce this issue with creating a new .blend file or without instructions on how to reproduce the issue. I will need a .blend file that reproduces the issue in order to look further into this.

\- Ryan

**Comment by semillerimages** [comment]
I really didn't do anything other than bake it. So for reproducing the problem, that's all I could tell you. So sorry :(
[scene-FF-4-good-hp-cameramove-2.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3040374/scene-FF-4-good-hp-cameramove-2.zip)

**Comment by rlguy** [comment]
Hi,

Thanks for attaching the .blend file. It looks like the problem is that your domain object has a smooth modifier with a few iterations of smoothing added. This will change the size of your domain will result in a difference between the 3d viewport and the size within the simulator. I would not recommend adding any modifiers to the domain object. You can add modifiers to the mesh objects, such as the fluid_surface object.

\- Ryan

**Comment by semillerimages** [comment]
Ahh, so sorry for not  realizing that :) Thank you much!
