### ISSUE TITLE
No simulation cache and crashes on Linux and MacOS. (Experimental 9.0.5.4)

### ISSUE THREAD

**Issue by Eugene619** [rlguy/Blender-FLIP-Fluids#445]
#### System Information

**Blender Version (including hash):** blender 2.79b and blender 2.8(f877022956df)
**FLIP Fluids Version:** 9.0.5.4
**Operating System:** Arch Linux
**CPU:** AMD Ryzen 1700x
**GFX:** Nvidia GTX 1080
**RAM:** 32gb

#### Bug

In version 9.0.5.4 I encountered bug with cache baking. It's seems that addon doesn't display baked cache. I tried blender 2.79b and blender 2.8. I had no luck. After checking blender output in terminal I haven't found what might cause that issue. 

![screenshot_20190510_002016](https://user-images.githubusercontent.com/24615487/57490479-ed21d380-72a8-11e9-95f5-1ec2786a2848.png)

However previous version of addon works perfectly. 

#### To Reproduce

Create new simple scene with cube as domain and sphere as a fluid. After try to bake fluid cache. I assume you need to use GNU/Linux distribution for that.

**Comment by rlguy** [comment]
Hi Eugene619,

Thanks for the report! From the console output that there is no fluid being generated by the sphere object (Fluid Particles: 0). I just made a quick test, but I was unable to reproduce this issue.

Would you be able to attach a .blend file that reproduces the issue? You may attach the file here by compressing it as a .zip file or by sending it to us at flip.fluids@gmail.com.

\- Ryan

**Comment by Eugene619** [comment]
Hi Ryan, 

Yes, I can attach that file. [test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3164283/test.zip)
Weirdly enough I don't have any issue with previous experimental version.

- Eugene

**Comment by rlguy** [comment]
Hi Eugene,

Thanks for the .blend file! I was just able to test this on my Linux system and I can confirm the issue. This issue will also be present on MacOS.

It looks like I had made a mistake building version 9.0.5.4 for Linux and MacOS. There were some fixes for Linux/MacOS and I had missed adding these fixes to the 9.0.5.4 version release. The issue was caused by a bug that could cause meshes to become corrupted in memory. This would result in meshes not being properly added to the simulator and could also result in crashes.

I have rebuilt the addon and have uploaded the fixed version to the Blender Market product downloads. Sorry for the inconvenience!

\- Ryan
