### ISSUE TITLE
Mesh artifacts on sloping surfaces

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#454]
#### System Information

**Blender Version: 2.79b (f4dc9f9d68b)**
**FLIP Fluids Version: 9.0.5.4**
**Operating System: Windows 7 64 Bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

On inclined surfaces there are artifacts of the mesh. These artifacts appear because the mesh generator tries to beat the surface of the obstacles. Perhaps this is a mesh generator error. Previously, these artifacts could have been avoided (in version 9.0.5.3). It was enough to turn off the mesh fit (turn off the Mesh Around Obstacles option). I know that I need to increase the size of the particles so that the artifacts become less noticeable. But this method does not suit me, because the liquid will look thicker. And an increase in the Subdivision parameter is not appropriate, since the mesh looks pimply. It seems to me that this problem needs to be solved by correcting the error in the mesh generator, and not by masking it with the Subdivisions and Particle Scale parameters. Or at least return to the old opportunity (from version 9.0.5.3), with the help of which it would be possible to disable the fitting of obstacles. Sometimes it is not critical if the mesh does not encircle the obstacle (when the fluid is opaque).

#### To Reproduce

[mesh_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3216725/mesh_test.zip)

#### Expected Behaviour

Add the ability to disable obstruction fit.

#### Actual Behaviour

Mesh always covers obstacles.

#### Screenshots
desired behavior:
![01](https://user-images.githubusercontent.com/7983249/58325859-c41a4a80-7e33-11e9-9543-126aab476514.jpg)

real behavior:
![02](https://user-images.githubusercontent.com/7983249/58325864-c8466800-7e33-11e9-9811-a01a831ab313.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! I had thought that the default settings for the new meshing options would prevent these artifacts but it looks like that is not the case for all situations.

I have added an option to disable meshing against obstacles and this will behave like in previous versions:

![disable_meshing_offset](https://user-images.githubusercontent.com/4285191/58361913-a73b4280-7e46-11e9-8af4-3882489c9146.jpg)

This will be included in the next version (1.0.5).

**Comment by PavelBlend** [comment]
@rlguy hello. I have a suggestion regarding mesh generation. I never use the Meshing Against Obstacles option as it creates annoying artifacts. Is it possible to project the fluid vertices onto the surface of the obstacle without changing the topology of the mesh? To get rid of artifacts. I've created an example using modifiers of how a mesh generator should roughly work:
![0](https://user-images.githubusercontent.com/7983249/221966820-fb252a4d-3a74-42d8-af85-9015db9bcbc4.png)
[test_mesh.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/10854363/test_mesh.zip)

I used Dynamic Paint and the Shrink Wrap modifier.

**Comment by rlguy** [comment]
Thanks for the suggestion! This looks like a nice result with the modifiers you have set up.

At the moment, the mesh generator works by generating polygons from volumetric data. Within the simulator, the obstacles and liquid are converted to volumes before generating a mesh. The general steps for when the Meshing Against Obstacles option is enabled:

1. Convert liquid particles and obstacle polygons to volumes.
2. Shrink or expand the obstacle volume according to Inside/On/Outside surface option.
3. Subtract the obstacle volume from the liquid volume. This removes the intersection of the liquid and obstacle, similar to a boolean.
4. Convert the liquid volume to polygons (The generated mesh is aligned to the grid using the [Marching Cubes Algorithm](https://en.wikipedia.org/wiki/Marching_cubes)).

Step number 3 is what can result in artifacts since this operation is removing data. This will tend to create artifacts aligned to the grid for thin layers of liquid. 

The default settings of "subdivisions = 1" and "Inside Surface" will tend to remove the least amount of data and result in less artifacts. Setting to "Outside Surface" will result in the most artifacts. For most use cases, the default options are a good choice for rendering, but there are certainly other cases where alternative settings are a requirement.

The proposed solution would keep all volume data and modify the polygon mesh afterwards:

1. Convert liquid particles to a volume.
2. Convert the liquid volume to polygons.
3. Project the polygon mesh vertices onto obstacle surfaces.

It looks like this works well from the example, but step 3 would be the difficult part to implement. There could be many edge-cases where the projection could produce a bad result that affects topology or can result in self-intersections. If this can be done well by Blender, then that would be a good solution to use outside of the simulator since these methods would already be implemented in Blender.

There may also be other methods that could be used to reduce meshing artifacts. However, I'm not sure when we'll be able to look further into this and experiment. Updates to the mesh generation methods may not receive any updates for quite some time.
