### ISSUE TITLE
Velocity and stream direction bias in viscosity solver

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#455]
#### System Information

**Blender Version: 2.79b (f4dc9f9d68b)**
**FLIP Fluids Version: 9.0.5.5**
**Operating System: Windows 64 bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

If the fluid has a low viscosity and the source of the fluid is small, then the fluid particles change their direction.

#### To Reproduce

Run a simulation in this scene:
[low_viscosity_test.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3220379/low_viscosity_test.zip)

#### Expected Behaviour

Liquid should fall vertically down.

#### Actual Behaviour

Jet fluid changes direction.

#### Screenshots

![low_visc_test](https://user-images.githubusercontent.com/7983249/58382811-9b32ba80-7fd7-11e9-872f-94d20e24b3bf.jpg)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! I have noticed this too, but I am not sure what causes this. It seems like there is a bias in the velocity direction when there is not very much grid coverage of the liquid.

It  could be possible that this is a limitation of the viscosity method/solver, but I will need to investigate this further to find out. The viscosity solver is quite complicated for me to modify, so this issue could take some time before I find a solution or answer to what the problem could be.

\- Ryan

**Comment by rlguy** [comment]
My apologies that this issue has taken so long to fix. I have tried a few times in the past to fix this, but with no success until today.

Recently I took another try at this issue by re-writing the viscosity solver from the start. During this re-write, I had noticed a simple mistake in the code. Part of the solver requires shifting the offset of a grid position by half of a voxel width. The mistake I made was that I had applied this offset twice in different areas of the code, leading to a total offset of 1 voxel instead of half of a voxel. This is what caused the stream to always have a bias in the +X/+Y/+Z direction.

This issue has been fixed and will be available in the next [experimental version](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Force-Field-Experimental-Builds), v9.0.9.15 (03-MAR-2021) or in the next stable version v1.0.9b (Release in early April).
