### ISSUE TITLE
search for gpu devices

### ISSUE THREAD

**Issue by MikelSotomonte** [rlguy/Blender-FLIP-Fluids#456]
I have updated my 1050 ti drivers, but this error keeps poping out.... any help? https://gyazo.com/00ae9fb0621c4a5a8bc20814fdf5fcef

**Comment by rlguy** [comment]
Hi MikelSotomonte,

If you have updated your drivers and are still getting the error, this could be caused by a mismatch between 32-bit and 64-bit Blender and FLIP Fluids. The FLIP Fluids version we distribute on the [Blender Market](https://blendermarket.com/products/flipfluids) is built as a 64-bit program and will only work within the 64-bit version of Blender.

If you have compiled/built the addon yourself, make sure that the version of Blender matches whether FLIP Fluids was built as a 32 or 64 bit program. If you are still getting this error after this, it could mean that your graphics drivers are not compatible with the program or that the program was built incorrectly.

In later versions of the addon we have [removed GPU features](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Frequently-Asked-Questions#is-the-flip-fluids-simulator-gpu-accelerated) and no longer require use of the GPU and graphics drivers. The most recent versions of the addon are currently available on the Blender Market. The next version of the addon (1.0.5) will be available within the next two weeks and we will also be updating the GitHub repository to this version.

Hope this helps!

\- Ryan

**Comment by MikelSotomonte** [comment]
I had tested it in a pc I have in a city close to mine and it worked just fine, but it could be something like that, I'm not that good at building and stuff like that. I really apreciate the help, thanks!

**Comment by Qzattitude** [comment]
Please use Blender 2.81 or 2.82 It worked for me. got the same errors. But I am baking fine now.
