### ISSUE TITLE
Add Mesh Erosion

### ISSUE THREAD

**Issue by nate066** [rlguy/Blender-FLIP-Fluids#458]
It would be cool if mesh erosion could be added as this would help thin some of the blobby splashes. Its also known as surface thinning/splash thinning. Its referenced in this paper https://www.cs.ubc.ca/~rbridson/docs/brentw_msc.pdf  section 3.9 page 23.

Using realflow heres an example of the diffrence

without erosion:
![rf_no_spash_thinning](https://user-images.githubusercontent.com/11403345/58833801-e07e6a00-861f-11e9-8fa9-2046643ede9d.PNG)

with erosion:
![rf_spash_thinning](https://user-images.githubusercontent.com/11403345/58833800-e07e6a00-861f-11e9-94b4-1391905b3dcb.PNG)

**Comment by rlguy** [comment]
Hi nate066,

Thanks for the request, but at the moment we are not accepting new large feature requests due to already having a long 'to-do' list of popular features ([Noted here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests)).

However, I do plan to add an improved mesh generator in the future. Rather than implementing the mesh erosion paper, I would prefer to implement this one: [Reconstructing Surfaces of Particle-Based Fluids
Using Anisotropic Kernels](https://www.cc.gatech.edu/~turk/my_papers/sph_surfaces.pdf). This is a paper that I have implemented in the past and I am more familiar with this method.

We also have a [sheeting effects](https://twitter.com/flipfluids/status/1089914805761331205) feature that is available in the experimental versions of the addon. This feature does not implement any improved mesh generation methods, but it helps with simulating thin splash effects.

\- Ryan
