### ISSUE TITLE
Rain simulation ?

### ISSUE THREAD

**Issue by gordielachance** [rlguy/Blender-FLIP-Fluids#472]
Hi ! I need to generate kind of a rain simulation.
I would like to use physics here because I want realistic droplets.
What I plan to do is to generate about 30 droplets emitter, then combine it in After Effects to simulate a rain falling.

Is that achievable with FLIP Fluids, and how would you do ?

Thanks !

**Comment by rlguy** [comment]
Hi gordielachance,

In general, I would not use a fluid simulator to simulate rain effects. This type of effect is not very common in a fluid simulator since the large amount of detail required to resolve fine rain droplets require high detail simulations and very large simulation times and memory requirements. Fluid simulation can be overkill for rain effects and there are simpler and quicker ways to achieve this effect.

It is more common to use Blender's particles systems combined with dynamic paint. There are a few tutorials for this effect on YouTube. Here is one for example: https://youtu.be/zpgnNktugro

For next time, please only use this issue tracker for bugs/issues. You may send questions to us through the Blender Market messaging system, email at flip.fluids@gmail.com, or on our [Facebook](https://www.facebook.com/FLIPFluids), [Twitter](twitter.com/flipfluids), and [BlenderArtists Thread](https://blenderartists.org/t/flip-fluids-addon-a-liquid-fluid-simulation-tool-for-blender). 

See our [technical support guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) for more info.

- Ryan

**Comment by gordielachance** [comment]
Hi,
Thanks for your reply.
I know about that (particles), it's just that I need to see the droplets
and have some details, not just a basic rain "sticks".  That why
(unhopefully) I need fluid simulation (unless something more convenient)
for this.
I don't have a floor so no need for wetmaps....

Thanks anyway.

**Comment by rlguy** [comment]
If using a fluid simulator, the simulation set up can be a bit more on the intermediate/advanced side and require some testing to get the right look. We have a surface tension feature that I would recommend using for small scale effects such as rain droplets and dripping. The simulation may require a high level of detail (high resolution) which leads to long simulation times and adding surface tension to the simulation can also add more time.

If you want to try out the simulator, we have a demo version with a few small limitations: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Demo-Addon

For creating rain droplets, I might suggest dripping fluid running off of an object that is out of view from the camera. Here is an example animation that shows some dripping with surface tension effects (see the drips off of the chin): https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Demo-Addon 

Surface tension helps create realistic drips by pulling droplets and masses of fluid together. Here is an exaggerated example of how higher surface tension forces pull fluid together: https://www.instagram.com/p/BuFPsdyAWxZ/

Creating multiple inflows that emit on/off during the simulation might work too. I would suggest shaping the inflows with irregular shapes so that surface tension forces will cause the fluid to change shape as the fluid falls.

Hope this adds some insight for how to achieve your effect!

**Comment by gordielachance** [comment]
Hi and thanks again for your help.

I have some more questions, not all related to flip fluids, it would be
awesome if you could help me since you've got a huge expertise !

1 / I think you give me the wrong like for the "drips of the chin" demo ?

2 / what I plan to do is to generate several simulation of one (or a few)
droplets, then duplicate them in After Effects to get a rain curtain, that
I would then duplicate along a Z axis (still in After Effects) to get a
complete rain.
The idea is to limit the fluids simulation time... What do you think ?

This is the kind of rain I want (this one is a previous test with Blender
Fluids) :
https://www.dropbox.com/s/rtg2d6epzg2ssza/fluidTest002-Cycles.mov?dl=1

3/ I've read that the domain (at least in the regular Blender fluid
simulation) is always a cube.
So if I have a domain of 1 meter height on .2 meter width, will the fluid
simulation take the same time than with a 1m*1m domain ?

4/ I've noticed that, with Blender Fluids, if I add "flow" keyframes on my
inflow, the simulation time takes up to 3 times more time. Do you know why ?

Well, any help would be grantly appreciated, your plugin seems really nice,
I have to see if I can achieve that effect.

Thanks a lot.

Benoît

**Comment by gordielachance** [comment]
+ how would you limit the amount of fluid emitted by a inflow object ?

Le mer. 7 août 2019 à 09:38, Benoît Gréant <gordie.lachance@gmail.com> a
écrit :

> Hi and thanks again for your help.
>
> I have some more questions, not all related to flip fluids, it would be
> awesome if you could help me since you've got a huge expertise !
>
> 1 / I think you give me the wrong like for the "drips of the chin" demo ?
>
> 2 / what I plan to do is to generate several simulation of one (or a few)
> droplets, then duplicate them in After Effects to get a rain curtain, that
> I would then duplicate along a Z axis (still in After Effects) to get a
> complete rain.
> The idea is to limit the fluids simulation time... What do you think ?
>
> This is the kind of rain I want (this one is a previous test with Blender
> Fluids) :
> https://www.dropbox.com/s/rtg2d6epzg2ssza/fluidTest002-Cycles.mov?dl=1
>
> 3/ I've read that the domain (at least in the regular Blender fluid
> simulation) is always a cube.
> So if I have a domain of 1 meter height on .2 meter width, will the fluid
> simulation take the same time than with a 1m*1m domain ?
>
> 4/ I've noticed that, with Blender Fluids, if I add "flow" keyframes on my
> inflow, the simulation time takes up to 3 times more time. Do you know why ?
>
> Well, any help would be grantly appreciated, your plugin seems really
> nice, I have to see if I can achieve that effect.
>
> Thanks a lot.
>
> Benoît
>
>

**Comment by gordielachance** [comment]
So this is what I've got so far.
The water is falling on a plane with a cloud texture animated on it to
distort it and add some details.
It's a first step but there is way too much water...
https://www.dropbox.com/s/fvhtwab4tsh0myb/flipFluids07.mov?dl=0

Do you think it is possible to tweak that to get a convincing result ?
Here's the project file in case you want to have a look :
https://www.dropbox.com/s/cfx6fwyenkjejsk/flipFluids07.blend?dl=0

Thanks

Benoît


Le mer. 7 août 2019 à 10:18, Benoît Gréant <gordie.lachance@gmail.com> a
écrit :

**Comment by rlguy** [comment]
Hi Benoit,,

Thanks for the video examples! I think I understand better now what you are trying to do.

1. Yes, you're right. I pasted the wrong link. Here is the correct animation: https://www.instagram.com/p/BurT0mllUiU/

2. I think that sounds like a good idea to reduce simulation time. More fluid as well as larger domain volume will increase simulation time.

3. In the FLIP Fluids simulator, the domain doesn't need to be a perfect cube, but it can be cuboid and have different width/height/depth. The smaller the domain volume, the quicker the simulation will run. Ideally, the domain should fit tightly around the fluid effect to maximize performance and detail, while minimizing memory usage. This documentation topic explains how to size the domain: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Object-Settings#how-large-should-i-make-my-domain-object

4. I'm not sure why this happens. It has been a while since I have used the Blender default fluid simulator.

5. There is a 'Constrain Fluid Velocity' option that can be helpful to limit the speed at which fluid is emitted from an inflow. Without this option enabled, gravity will immediately pull down the fluid which leads to a lot of fluid being emitted. We have documentation for how this setting can be used here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Constrain-Fluid-Velocity-Additional-Notes

---

I just had a chance to check out your .blend file and test some simulation setups. I think the easiest simulation setup would be to create a few inflows and keyframe the 'Enabled' option on/off. In this setup I added a noise modifier in the graph editor:

![rain_example](https://user-images.githubusercontent.com/4285191/62654421-99a93b00-b914-11e9-926a-322c3b8db45a.jpg)

Animation example: https://gfycat.com/commonmetallicfinnishspitz

.blend file: https://www.dropbox.com/s/f8r4zre9o556bbf/rain_example.blend?dl=0

It could take some tweaking of the noise to get the inflows to turn on/off at a good rate.

Here are some notes on the domain settings:
- **Surface Panel > Subdivisions set to 1**. This creates a higher detail mesh which would be good for small droplets.
-  **Surface Panel > Particle Scale set to 1.00**. This is the default value and I would not suggest setting this value lower than 1.00. Setting this value lower can produce meshes with missing data. If you want small droplets, you will need to increase simulation resolution and/or make inflows smaller. [Surface mesh generation documentation here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Surface-Settings#mesh-generation-quality).
- **World Panel > Surface Tension set to 0.05**. This helps create more realistic droplets, but will add quite a bit more simulation time.
- **World Panel > Surface Tension Accuracy set to 98%**. Increasing this value adds more time to the simulation, but produces better surface tension results. This value often needs to be set higher for smaller scale simulations such as droplets. [Surface Tension Documentation here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#surface-tension)
- **Advanced Panel > PIC/FLIP Ratio set to 0.40**. Increasing this value can help with creating smaller scale simulation effects. The default value of 0.05 is good for splashy chaotic simulations such as oceans, but can be too wild for small scale effects. [Documentation here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Advanced-Settings#simulation-stability).
- I added a 'Smooth' modifier to the fluid_surface object. This helps smooth out bumps int he fluid surface and I do this for most of my simulations.

Hope this helps!

\- Ryan

**Comment by gordielachance** [comment]
Ryan, you are the boss !
Thanks a lot for your wisdom here.  It will help me understand those complex things better.
Your notes are particulary helpfull.  Just one thing : I read things about "surface tension" here and there. What is it exactly ?
 I'll let you know if I have some progress on that !
Thanks again.

**Comment by rlguy** [comment]
No problem, glad to help! Surface tension is a natural force that pulls molecules on the surface of the fluid together. You can think of it like a weak elastic material that is wrapped around the fluid surface. This is the force that causes water and other liquids to form into drips, beads, and join together.

From a distance, surface tension forces are not that noticeable, such as in a splashy ocean. So for large scale liquids, you can often ignore surface tension and leave this setting disabled. But up close for small scale liquids, surface tension forces become much more noticeable. For small scale liquid effects, enabling surface tension makes the fluid look and behave more realistically.

Here is an animation that compares different amounts of surface tension: https://twitter.com/FlipFluids/status/1066870859753644032
