### ISSUE TITLE
Error when baking 'unable to load fluid engine library'

### ISSUE THREAD

**Issue by MikelSotomonte** [rlguy/Blender-FLIP-Fluids#473]
This happnes when I try to bake any simulation. <blpyfluid.dll> is in the flip_fluids_addon\pyfluid\lib directory, so I don't know how to fix the problem. I have checked that blender and python are both x64 as well as the addon.
![Captura](https://user-images.githubusercontent.com/45179289/62835911-edda5500-bc5d-11e9-8b18-ed5ef06ab24e.PNG)
![Captura2](https://user-images.githubusercontent.com/45179289/62835921-00548e80-bc5e-11e9-8342-f028f2c43e6d.PNG)

**Comment by rlguy** [comment]
Hi MikelSotomonte,

It looks like you are using an unsupported compiler (Microsoft Visual Studio Compiler). We have a note about this in the [build instructions](https://github.com/rlguy/Blender-FLIP-Fluids#source-code-dependencies) and displayed when running the [CMake script](https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/CMakeLists.txt#L71):

> WARNING: Compilation using MSVC (Microsoft Visual Studio Compiler) is experimental and not officially supported. Building with MSVC may result in errors and performance issues.

For Windows, we use the MinGW compiler since we have not had success building with the MSVC tools.

For next time, please be aware that this issue tracker is only meant for issues related to the official add-on version distributed through the Blender Market. See this document for technical support guidelines: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines

\- Ryan
