### ISSUE TITLE
Unable to recover deleted surface

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#483]
#### System Information

**Blender Version: 2.81 (rB26bd5ebd42e3)**
**FLIP Fluids Version: 1.0.7**
**Operating System: Windows 7 64 bit**
**CPU: AMD A8-5600K**
**GFX:-**
**RAM: 8GB**

#### Describe the bug

If you remove the fluid_surface object, then the fluid cannot be restored.

#### To Reproduce

- Create any simulation.
- Bake liquid
- Remove fluid_surface object
- Make a new bake
- fluid_surface object will not be created.

#### Expected Behaviour

If there is no fluid_surface object in the scene, then you need to create it.
One could add a new parameter to the domain object, which would point to the liquid object.

#### Actual Behaviour

I do not know how to restore fluid_surface.

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! This is an interesting bug. If you delete the fluid_surface object from the viewport, the object is not actually removed from the .blend file and remains. If you delete the fluid_surface object in the outliner, it is completely removed from the .blend file.

This bug happens because the addon can still find the object in the .blend file even though it is not in the viewport. The addon thinks there is a valid fluid_surface object, so it does not regenerate the object.

### Workaround

A workaround to to recover the fluid_surface is to manually delete the object in the .blend file data. This can be done in the _Blender File_ view of the outliner:

![blender_file_data](https://user-images.githubusercontent.com/4285191/70464757-5ef71100-1a74-11ea-88cb-8caa5a73e157.png)

### Bug Fix

This has now been fixed. The addon will properly detect if it needs to regenerate the fluid_surface (and whitewater) mesh objects.

If you would like to apply this fix to your addon installation now, you can replace a script. Unzip the following file to get **flip_fluid_cache.py**:

[flip_fluid_cache.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3941328/flip_fluid_cache.zip)

Replace the **flip_fluids_addon/objects/flip_fluid_cache.py** with the fixed file and restart Blender.

**Comment by PavelBlend** [comment]
I replaced the flip_fluid_cache.py file with your corrected version.
But the error is still present.
Removing an object through an outliner window does not help.
Here is the scene in which this error is reproduced:
[twix_chocolate.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3998775/twix_chocolate.zip)

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for letting me know! I just had a chance to test this with your .blend file. It looks like just patching v1.0.7 with the script will have some problems with recovering the fluid_surface. In our current development version, this seems to work properly, so there may be some interactions with some other scripts that won't work with the simple script update.

I'll leave this issue open and do some more testing. I have reported this issue to the Blender developers to see if the different behavior of deleting in the viewport vs the outliner is actually a bug: https://developer.blender.org/T72960

\- Ryan

**Comment by rlguy** [comment]
This fix in now included in FLIP Fluids v1.0.8. This fix may only apply to newly created .blend files.

To attempt to repair an older .blend file, remove the fluid_surface object from the blend file data, switch back to the outliner view layer mode, and reload the frame. The addon is unable to properly generate new objects when the outliner view is displaying blend file data.
