### ISSUE TITLE
[Blender 2.8x] Add option to set OpenGL point size for particle debugging

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#484]
#### System Information

**Blender Version (including hash): 2.81 (sub 16), branch: master, commit date: 2019-12-04 11:32, hash: `rBf1aa4d18d49d`**
**FLIP Fluids Version: 1.0.7**
**Operating System: Windows 7 64 bit**
**CPU: AMD A8 5600K**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

Particle Size (Debug Panel) has disappeared in Blender 2.81.

#### Expected Behaviour

You can do it as follows:
```bgl.glPointSize(particle_size)```

#### Actual Behaviour

There is no way to specify the particle size.

**Comment by rlguy** [comment]
Hi PavelBlend,

Thanks for the report! We had to remove the option to set pointsize for Blender 2.8x. The addon uses the new Blender 2.8x drawing system which uses the ```gpu``` module that uses vertex and fragment shaders instead of the old ```bgl``` module. As far as I could find, there is not a way to specify the point size in the gpu module.

Here is a code snippet of the shaders that we're using in Blender 2.8x:

```python
vertex_shader = """
    uniform mat4 ModelViewProjectionMatrix;
    uniform float pointsize;

    in vec3 pos;
    in vec4 color;

    out vec4 finalColor;

    void main()
    {
        gl_PointSize = pointsize;
        gl_Position = ModelViewProjectionMatrix * vec4(pos, 1.0);
        finalColor = color;
    }
"""

fragment_shader = """
    in vec4 finalColor;
    out vec4 fragColor;

    void main()
    {
        fragColor = finalColor;
    }
"""

particle_shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
particle_shader.uniform_float('pointsize', dprops.debug.particle_size)
particle_batch_draw = batch_for_shader(
    particle_shader, 'POINTS',
    {"pos": particle_vertices, "color": particle_vertex_colors},
)
```

We are setting the OpenGL pointsize in the shader with ```gl_PointSize = pointsize;```. But this does not seem to affect how it is actually drawn in the Blender viewport when changing the size. I had posted a questions about this on the Blender Artists forums, but did not receive an answer. I may need to try the https://devtalk.blender.org/ forum to ask the developers why this does not work.

**Comment by PavelBlend** [comment]
Everything works in my jet fluids addon:
https://github.com/PavelBlend/blender_jet_fluids_addon/blob/master/jet_fluids/render.py#L48
I ported it to blender 2.80.
Despite the fact that I am using the gpu module, I still specify the size of the points using the bgl module:
![01](https://user-images.githubusercontent.com/7983249/70933900-d1a45580-204d-11ea-980d-8388d809e6df.jpg)

**Comment by rlguy** [comment]
Thank you so much for the tip! This fixes the problem. I did not know the bgl module would work like this.

I have added this fix to the addon. If you would like to add this fix to your installation, unzip the following file:

[issue_484_patch.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/3969747/issue_484_patch.zip)

And replace the scripts at these locations:
- ```flip_fluids_addon/ui/domain_debug_ui.py```
- ```flip_fluids_addon/operators/draw_operators.py```
