### ISSUE TITLE
Inflow does not stop when disabled

### ISSUE THREAD

**Issue by nokodi** [rlguy/Blender-FLIP-Fluids#486]
#### System Information

**Blender Version (including hash):** v2.81a
**FLIP Fluids Version:** 1.05
**Operating System:** Windows 10 Pro
**CPU:** Intel Core i7-8700
**GFX:** GeForce RTX 2070
**RAM:** 16 GB

#### Describe the bug
I try to create a single drop of fluid that is dripping out of a tube. Therefore I enable the inflow with a key frame from the start of the animation. After one frame, I disable the inflow with a key frame (see attached blend file). 

#### To Reproduce

Run the attached simulation.

#### Expected Behaviour

Only one drop of fluid coming out of the tube and than dripping down to the floor.

#### Actual Behaviour

It looks like fluid is coming out of the inflow for just one frame as desired but when the simulation continues, it seems that the amount of fluid in the tube is constantly growing although the inflow does not produce fluid anymore (see attached blend file).

#### Screenshots

[my_second_simulation.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/4000000/my_second_simulation.zip)

**Comment by rlguy** [comment]
Hi nokodi,

This is caused by a side effect of the sheeting feature. See the documentation notes on the **Sheeting Strength** parameter for more information and how to reduce this effect: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#sheeting-effects

The **Sheeting Strength Multiplier** against the Cylinder object can also be keyframed or set to 0 to specifically reduce sheeting in proximity to the obstacle: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings#obstacle-properties

\- Ryan
