### ISSUE TITLE
Addon builds but is missing in installed plugins after copying to appropriate directory

### ISSUE THREAD

**Issue by ss32** [rlguy/Blender-FLIP-Fluids#487]
#### System Information

**Blender Version (including hash):**
2.81a, commit f1aa4d18d49daf483c54f35e3e2e629f7b3a925c, built from source

**FLIP Fluids Version:**
v1.0.7 commit afafa4466c78136a1b2b85e17bc138fef9b258c5

**Operating System:**
Linux Mint 18.3 (Ubuntu 16.04 LTS base)
Kernel 4.12.0-041200-generic

**CPU:**
Intel Core i5-3570K

**GFX:**
Nvidia GTX-1080ti
Driver 418.87
Cuda 10

**RAM:**
24Gb

#### Describe the bug

Built from the git repo, copied `bl_flip_fluids` directory to `$HOME/.config/blender/2.81/scripts/addons/`, launched Blender and the addon doesn't show up in installed addons.

#### To Reproduce

```
git clone https://github.com/rlguy/Blender-FLIP-Fluids.git
cd Blender-FLIP-Fluids
mkdir build
cd build
cmake .. -G "Unix Makefiles"
make -j4
cp -r bl_flip_fluids/ $HOME/.config/blender/2.81/scripts/addons/
```

Launch Blender, check addons in *Preferences-->Addons*

#### Expected Behaviour

I expect that the addon shows up in the menu

#### Actual Behaviour

The addon does not show up in the list of addons

#### Screenshots

[Blender splash screenshot](https://imgur.com/a/rxnGmGW)
[Addon lists screenshots](https://imgur.com/a/hGfaz0I)

edit: [Screenshot: GPU recognized in blender](https://imgur.com/a/w02RdjW)

**Comment by rlguy** [comment]
Hi ss32,

Once built successfully, the addon folder should be located here: ```bl_flip_fluids/flip_fluids_addon```.

The ```bl_flip_fluids/flip_fluids_addon``` directory should be copied into to the ```2.81/scripts/addons/``` folder. There should be a file ```bl_flip_fluids/flip_fluids_addon/__init__.py``` that tells Blender how to register this addon.

For future reference, this issue tracker is only meant for reporting bugs for the FLIP Fluids product distributed on the Blender Market. We are not able to provide support on compiling the GitHub source. See our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines).

\- Ryan

**Comment by ss32** [comment]
>We are not able to provide support on compiling the GitHub source. See our Technical Support Guidelines.

I appreciate the quick feedback, and that the source is available for testing.  Is no official channel for issues with the source?  I'd be happy to take this elsewhere.

For posterity, I have `flip_fluids_addon` in the proper directory but it still fails to load.  It would be great if there was some way to verify the installation to avoid these types of issues.
```
~/.config/blender/2.81/scripts/addons $ ls flip_fluids_addon/
bake.py          icons           materials  presets     render.py  types.py
exit_handler.py  __init__.py     objects    properties  resources  ui
export.py        __init__.py.in  operators  pyfluid     source     utils
```


```
$ sha1sum flip_fluids_addon/__init__.py
f5d7f50dc64cea6a4fae04839a2ad043f0f12ce7  flip_fluids_addon/__init__.py
```

**Comment by rlguy** [comment]
Great to hear that this is now solved! Addons need to be activated manually after install. 

Another way to install the addon using the Blender interface is to create a .zip file that contains the ```flip_fluids_addon``` folder. And then install through Blender with **Edit > Preferences > Add-ons > Install** and select the .zip file. Blender will then automatically unzip the file into your ```scripts/addons``` location and display the addon entry for activation.

We do not have an official channel for direct support regarding building or installing the addon. We are a small team and have limited time resources for support and development. Due to the wide variety of development environments and experience of those building the project, providing full support and troubleshooting for building the source can take some time away from development. We'd love to be able to help everyone, but we need prioritize support for the customers on the Blender Market since this is what funds the development of the FLIP Fluids project.
