### ISSUE TITLE
Playback Offset gives inconsistent results

### ISSUE THREAD

**Issue by rainChu** [rlguy/Blender-FLIP-Fluids#488]
#### System Information

**Blender Version (including hash):** 2.81a (f1aa4d18d49d)
**FLIP Fluids Version:** 1.0.7
**Operating System:** Windows 10
**CPU:** Intel i7-4790 @ 3.60GHz
**GFX:** GTX 1060, 6GB
**RAM:** 16GB

#### Describe the bug

When either previewing or rendering, a playback offset other than 0 doesn't give consistent results. For instance, sometimes the fluid mesh won't change, and sometimes it will. This is especially common when Playback Offset is set to 1 or -1.

#### To Reproduce

Create a small fluid simulation with only 8 or so frames. Nothing other than one fluid inflow is needed to see the results. Bake the results, and set Playback offset to 1. Increment the frame one by one using right arrow. The cache will update only other frame. Move backwards by one by one, and notice that it updates fine.

#### Expected Behaviour
I expected a playback offset to be deterministic..

#### Actual Behaviour

Playback Offset seems to depend on an async call (possibly hard disk access?) and isn't consistent.

#### Screenshots

https://rainChu.com/s/oRuuXEnO.mp4

**Comment by rlguy** [comment]
Hi rainChu,

Thank you for the report and video! I am able to reproduce this issue from the instructions.

It looks like this is caused by a bug in the scripts that are run during a frame change. In some areas of the scripts, the _playback offset_ value was not being used when calculating which frame to load, leading to an inconsistent frame number. This ended up being most noticeable when the _playback offset_ was set to -1 or 1, but can still happen at other values.

I have fixed this issue for the next version.

\- Ryan
