### ISSUE TITLE
How to enable/disable outflow via script?

### ISSUE THREAD

**Issue by GuyJan** [rlguy/Blender-FLIP-Fluids#490]
I am trying to enable and disable an outflow at specific frames. Using keyframes, everything works fine. Then I tried to do the same via a command in a  script handling frames, using the command lines:

```python
bpy.data.objects["Condensor_OutLow"].flip_fluid.outflow.is_enabled = True
print(bpy.data.objects["Condensor_OutLow"].flip_fluid.outflow.is_enabled)
bpy.data.objects["Condensor_OutLow"].flip_fluid.outflow.is_enabled = True
print(bpy.data.objects["Condensor_OutLow"].flip_fluid.outflow.is_enabled)
```

Running the script, the outflow seems to be enabled and disabled at the right frames. However, after baking, the command was not executed, and nothing happens. 
Do I have to import a module?

**Comment by rlguy** [comment]
Hi GuyJan,

If you are modifying any addon properties in a script handler (such as ```frame_change_pre``` or ```frame_change_post```), this will not have any effect on the simulations. This is because the simulation runs in a separate thread detached from Blender. In this separate thread, there is no access to the Blender Python API and it will not trigger any scripts in Blender.

At the start of a simulation after pressing the _Bake_ operator, the addon exports all of the simulation settings for the entire simulation before launching the baking thread. The addon is only able to export property data that is keyframe animated.

To set the Outflow _Enabled_ property using a script, you will need to script this in a way that adds keyframes to the property. Here is an example for how this can be done:

```python
import bpy

def get_enabled_value_at_frame(frameno):
    # returns True every 10 frames, False otherwise
    return frameno % 10 == 0


outflow_object = bpy.data.objects.get("Outflow")
domain_properties = bpy.context.scene.flip_fluid.get_domain_properties()
frame_start, frame_end = domain_properties.simulation.get_frame_range()

# For each frame, set the is_enabled property and insert a keyframe
# keyframe_insert documentation: 
#    https://docs.blender.org/api/current/bpy.types.bpy_struct.html#bpy.types.bpy_struct.keyframe_insert
for frame in range(frame_start, frame_end):
    outflow_object.flip_fluid.outflow.is_enabled = get_enabled_value_at_frame(frame)
    outflow_object.keyframe_insert("flip_fluid.outflow.is_enabled", frame=frame)
    print("Frame: ", frame, "is_enabled: ", outflow_object.flip_fluid.outflow.is_enabled)
```

This script example will enable an outflow every 10 frames. Here is a link to an example .blend file that includes this script:

https://www.dropbox.com/s/xtxx8b7luhbl8ms/keyframe_script_example.blend?dl=0

Press the _Run Script_ button before running the simulation.

Does this answer your question?

\- Ryan

**Comment by GuyJan** [comment]
Hello rlguy,

Thanks for your quick reply. I will try this out.

Br,

Guy

**Comment by rlguy** [comment]
I'll be closing this issue thread due to inactivity. If you have any updates, feel free to comment or send us a message at flip.fluids@gmail.com
