### ISSUE TITLE
std::bad_alloc thrown at start of bake

### ISSUE THREAD

**Issue by Sciguy429** [rlguy/Blender-FLIP-Fluids#494]
#### System Information

**Blender Version (including hash): 2.82 (sub 7) build_hash: b'375c7dc4caf4**
**FLIP Fluids Version: 1.0.8a**
**Operating System: Windows 10 Pro**
**CPU: Ryzen 1700x**
**GFX: GTX 1080TI (11GB Vram)**
**RAM: 16 GB**

#### Describe the bug

> Blender hard crashes when baking, immediately after finishing exporting animated meshes. My blend file is made up of a simple environmental mesh and two complex animated characters (~80K verts). Only one of the two meshes interacts with the fluid, the other had no FLIP constraints applied. Last night I managed to bake a low quality test version of the simulation and it worked perfectly fine. However when I went to bake a much higher res version this morning this error started occurring.
> 
> It took me awhile but I think I figured out what is happening. Last night the inflow was a simple static mesh, however the only change I made this morning was adding a Copy Location object constraint to it. For whatever reason the Export Animated Mesh option was selected by default and I didn't even notice it. Upon turning this option off the bake worked perfectly.
> 
> I guess FLIP Fluids doesn't quite know what to do when there are two separate control structures acting on a mesh.
> 
> #### To Reproduce
> 
> Unfortunately, I can't upload my blend file, however the issue seems to be easily repeatable. All you need is a Domain containing an object with Copy Location constraint and exported animated mesh selected. The crash should occur regardless of other variables.

So Uhh, scratch all of that speculation, one of the other things I did was add an obstacle constraint to my environment, so the liquid wouldn't clip thought it. The issue is my environment mesh is freaking massive, part of it is a large plane that just stretches out past the render distance. Upon removing the obstacle on that mesh the issue fully disappeared. Perhaps there should be a warning for when a large obstacle is detected? That plane was so large it likely overflowed some variables.....

Anyways reproducing this should be super easy, just scale an obstacle plane up until it crashes.

[Bad_Alloc-Error.txt](https://github.com/rlguy/Blender-FLIP-Fluids/files/4582856/Bad_Alloc-Error.txt)

**Comment by rlguy** [comment]
Hi Sciguy429,

Thanks for the report! However, this is working as expected. When obstacles become much larger than the domain, you may run out of memory. This is because in order to calculate what parts of the object are inside/outside of the object's volume, a large grid needs to be wrapped around the entire object. If the grid becomes too large, you will run out of memory.

I have just added a documentation note about this here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings#does-my-obstacle-object-need-to-be-completely-contained-by-the-domain

> ### Does my obstacle object need to be completely contained by the domain?
>
> No, it is okay for your object to be larger than the domain. However, we do not recommend the object to be very large compared to the domain size. Objects much larger than the domain will require more RAM and can slow down computation or you may even run out of memory. For very large objects, you may want to create smaller trimmed down proxy object for use in the simulator.

At the moment, the addon does not detect or provide any feedback on settings or meshes that can cause potential problems, but this would be a helpful feature to have! There are many potential issues that are possible to detect. It's on a list of things to consider for future development.

\- Ryan
