### ISSUE TITLE
Viscosity/Friction: Fluid sticking to obstacles

### ISSUE THREAD

**Issue by majormongoose** [rlguy/Blender-FLIP-Fluids#496]
Hello, I am having an issue with fluid sticking my obstacles ( icing sticking a donut in this case). I want the icing to just roll off the donut into the outflow, but for some reason the chocolate icing will just hang suspended from the donut after it is initially poured on. I am using the low viscosity settings and a friction value of about .2 on my donut. Any idea what is going on here? 
![image](https://user-images.githubusercontent.com/66112697/83237107-a7110980-a162-11ea-823f-4336b25a25d3.png)

**Comment by rlguy** [comment]
Hi majormongoose,

From the screenshot, it looks like this issue could be caused by the sheeting effects feature. This feature fills in gaps between separating fluid particles and if left enabled, this can lead to fluid hanging/dripping indefinitely. See this documentation on the setting for a way to resolve this issue (keyframe sheeting strength or obstacle sheeting down to 0.0): https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#sheeting-effects

As far as I can tell, the simulator is working as expected, so I would not consider this as a bug. If you need help with a scene troubleshooting issue, see our documentation [Guidelines for Requesting Scene Troubleshooting Help](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Requesting-Scene-Troubleshooting-Help).

\- Ryan
