### ISSUE TITLE
[question] Uncertain "PIC/FLIP Ratio" parameter's name or description

### ISSUE THREAD

**Issue by thima2017** [rlguy/Blender-FLIP-Fluids#499]
It's not a bug report, so don't follow the bug report guide.

![Untitled](https://user-images.githubusercontent.com/32433505/85253759-8be6a080-b467-11ea-85e5-ad4f978701d7.png)

I guess either there should be another description or name of the option.
This is what description appears now:
```
            description="Ratio of PIC velocity to FLIP velocity update mixture."
                " PIC velocity method is not very accurate, but stable. FLIP"
                " velocity method is very accurate, but less stable. Using a"
                " value of 0.0 results in a completely FLIP simulator, while"
                " using a value of 1.0 results in a completely PIC simulator"
```
I think it should be:
```
            description="Ratio of PIC velocity to FLIP velocity update mixture."
                " PIC velocity method is not very accurate, but stable. FLIP"
                " velocity method is very accurate, but less stable. Using a"
                " value of 1.0 results in a completely FLIP simulator, while"
                " using a value of 0.0 results in a completely PIC simulator"
```
And as far as this my first guess appears wrong, I think the option should be named as "FLIP/PIC Ratio" instead of "PIC/FLIP Ratio".  For better intuitive understanding. FLIP to left (0), PIC to right (1). Or "PIC factor" with the current description. I didn't get that it's a fraction where FLIP always is 1, until I looked in the code. I thought PIC is when the slider is on the left and FLIP is when the slider is on the right. So I've understood it now. You may close this issue without reading. If my English was really wronk that because polite people are everywhere. Nobody told me.

**Comment by rlguy** [comment]
Hi thima2017,

We use the naming convention of PIC/FLIP to mean PIC to FLIP Ratio. Meaning that if set to the default 0.05, this means there is 0.05 PIC and the rest is FLIP (0.95).

A value of 0.0 will be completely FLIP and a value of 1.0 will be completely PIC.

Some simulators instead name this setting the FLIP/PIC (FLIP to PIC ratio), where the values are reversed and they use a value of 1.0 to mean completely FLIP.

The only reason why we use PIC/FLIP instead of FLIP/PIC is because the textbook we used to implement this simulator used the PIC/FLIP meaning.

We will likely not change this setting from PIC/FLIP to FLIP/PIC, since this setting has been like this in the addon for over two years and do not want to cause confusion by changing it.

I thought your English was good. 

Hope this info helps!

\- Ryan
