### ISSUE TITLE
Fluid instability at a dense resolution / domain ratio

### ISSUE THREAD

**Issue by fabricatedmath** [rlguy/Blender-FLIP-Fluids#501]
#### System Information

**Blender Version (including hash):** 2.90 0330d1af29c0
**FLIP Fluids Version:** flip_fluids_addon-1.0.8a_stable_05-mar-2020
**Operating System:** Ubuntu 20.04
**CPU:** AMD Ryzen Threadripper 3970X
**GFX:** Nvidia 2080ti
**RAM:** 256G

#### Describe the bug

Fluid blows up at frame 2 of an animation with surface tension and sheeting effects, but only at certain scales, keeping all other domain parameters the same. This is roughly the setup for your flip text animation:
![flip-before-scaling-frame2](https://user-images.githubusercontent.com/36798976/93010029-c8e99d00-f555-11ea-9f4a-404ab04064e2.png)

This is frame 2 after dragging the domain size inwards:
![flip-after-scaling-frame-2](https://user-images.githubusercontent.com/36798976/93010043-eae31f80-f555-11ea-95ee-f1154ed7264b.png)

#### To Reproduce

Here is a .blend with both scenes and screenshots
[flip-fluid-instability.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/5213615/flip-fluid-instability.zip)

#### Expected Behaviour

Not blow up

#### Actual Behaviour

blow up

#### Screenshots

See above

### Extra

I think I saw a post about this, but couldn't find it in active issues, something about surface tension being a pain. Don't get me wrong, I'm sure something like this is nuts to nail down, but do you have any heuristics or ratios of what domain settings to use to avoid explosions like this? Not really prepared to do a binary search on the domain size to see when stuff like this starts to happens, or for which surface tensions/sheeting values.

Thanks!

**Comment by rlguy** [comment]
Hi Charles,

Thanks for the report and attaching the .blend files! The good news is that this can be fixed with a modification of the domain settings. The more difficult to track down bugs/instabilities are simulations where the fluid begins stable and then spontaneously 'explode' ([See animation in this comment for an example](https://github.com/rlguy/Blender-FLIP-Fluids/issues/420#issuecomment-636128261)).

It looks like the issue in the scene is related to the surface tension feature and the _Estimated Substeps_ value. See the documentation notes on the [Estimated Substeps (inflo) here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-World-Settings#surface-tension):

> **Estimated Substeps (Info)**
>
>Displays the estimated number of substeps per frame that the simulator will run in order to keep simulation stable during surface tension computation. This number will depend on domain resolution and size, framerate, amount of surface tension, and surface tension accuracy.
>**NOTE:** The number of estimated substeps may exceed the Max Substeps value in the Advanced Settings panel. In this case, the Max Substep value should be increased to at least the number of estimated substeps.
Related Documentation: [What are substeps, and how do the min, max, and CFL parameters relate to each other?](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Advanced-Settings#what-are-substeps-and-how-do-the-min-max-and-cfl-parameters-relate-to-each-other).

The number of estimated substeps is related to the domain size and resolution. As the voxels become smaller, the number of substeps will increase:

(Left: before scaling, Right: after scaling)
![estimated_substeps](https://user-images.githubusercontent.com/4285191/93114797-e9a61580-f66f-11ea-9b5e-8ff67e2ef80c.jpg)

The reason why the simulation is exploding immediately is because by default, the maximum number of substeps the simulator is allow to take is 24, while the estimated number due to surface tension is at 48. In order to keep the simulation stable, you will need to increase the maximum substeps value in the [FLIP Fluid Advanced panel](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Advanced-Settings#frame-substeps) to at least 48.

Notes and Tips:
- A simulation requiring 48 substeps for surface tension would indicate quite a large amount of surface tension and I would not recommend this as it would take a very long time to simulate. I usually try to design my simulations to take less than 8 substeps. The FLIP simulation method starts losing it's speed advantage over other simulation methods as the number of required substeps gets higher.
- For high surface tension simulations, a lower resolution often produces a better and more stable result than a high resolution simulation.
- If you want to maintain a constant grid density (voxel size) as you resize the domain, enable the _Lock Cell Size_ option under the domain resolution setting.
- Enable the Display Grid option in the FLIP Fluid Debug panel to visualize how the grid changes as you resize the domain or change resolution.

Hope this info helps!

\- Ryan

**Comment by fabricatedmath** [comment]
Hey, thanks so much! This is starting to make more sense to me.

**Comment by Shaggy90** [comment]
It would be super cool to have some warning when the estimated substeps exceed your maximum settings. Could we have some "[!]Estimated substeps higher than maximum set in FLIP Fluid Advanced Settings"? I didn't want to mess around with advanced settings and turns out I had to. I wasted so much time trying to figure it out. :P
