### ISSUE TITLE
[feature request] inflow and outflow matching

### ISSUE THREAD

**Issue by guitartom47** [rlguy/Blender-FLIP-Fluids#503]
Would it be possible for the FLIP addon to have an outflow on one side of the domain that exactly matches the inflow on the opposite side, or to have fluid flow through at a specific speed and depth as if there were no boundaries? This would be wonderful for ship or boat representations. A quick example: 
https://www.youtube.com/watch?v=XrF4FIcHs84

**Comment by rlguy** [comment]
Hi,

A current work around for this is to set up two inflows on each size of the domain to push fluid in a constant velocity (using [Constrain Inflow Velocity](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Inflow-Constrain-Fluid-Velocity-Additional-Notes) option). An outflow at one of the ends removes the fluid. This creates a conveyer belt-like fluid simulation that we've seen other ship simulation creators use.

Another trick to maintain a constant open ocean water level is to place outflows at the domain edges above the water level. This will remove fluid that becomes too high. Inflows placed at the domain edges underneath the water level will add fluid in the case that the water becomes too low.

We are currently focusing on a force field feature set (#500), but afterwards we will be moving on in 2021 to create an ocean simulation toolset to help automate these processes. We've already started some of the work for this over the past year. Some notes:

- We'll be adding open boundaries to automate an ocean water level.
- The domain position and size will be animatable. So rather than use a conveyer belt work around, ship simulations can be done by animating both a ship and a domain through an ocean with a specified water level. This is how other simulation software such as Phoenix FD and Houdini work for moving ship simulations.

The ocean toolset is a smaller part of a larger project to re-design the simulation engine and addon to use an adaptive domain (Specifically a sparse domain where only '_interesting_' parts of the domain are simulated). Adaptive domain is a pre-requisite for some of the ocean toolset features we will be adding. We'll add more details to this project to issue #286 (Adaptive Domain) once we move our priority after finishing the force field feature set. For now, we'll close this issue.

\- Ryan

**Comment by guitartom47** [comment]
Hey Ryan, 

I helped a friend who was working on an Italian beer ad recently and we used your addon for Blender. if you wanted your community to see it here's the link: VITTORIA PER BRINDARE INSIEME

 
 
 
   
 VITTORIA PER BRINDARE INSIEME
    
I didn't know how to inform you otherwise, but I think this is pretty cool.








On Tuesday, November 10, 2020, 12:59:56 PM CST, Ryan Guy <notifications@github.com> wrote: 







Hi,

A current work around for this is to set up two inflows on each size of the domain to push fluid in a constant velocity (using Constrain Inflow Velocity option). An outflow at one of the ends removes the fluid. This creates a conveyer belt-like fluid simulation that we've seen other ship simulation creators use.

Another trick to maintain a constant open ocean water level is to place outflows at the domain edges above the water level. This will remove fluid that becomes too high. Inflows placed at the domain edges underneath the water level will add fluid in the case that the water becomes too low.

We are currently focusing on a force field feature set (#500), but afterwards we will be moving on in 2021 to create an ocean simulation toolset to help automate these processes. We've already started some of the work for this over the past year. Some notes:

     
    * We'll be adding open boundaries to automate an ocean water level.
    
    * The domain position and size will be animatable. So rather than use a conveyer belt work around, ship simulations can be done by animating both a ship and a domain through an ocean with a specified water level. This is how other simulation software such as Phoenix FD and Houdini work for moving ship simulations.
    

The ocean toolset is a smaller part of a larger project to re-design the simulation engine and addon to use an adaptive domain (Specifically a sparse domain where only 'interesting' parts of the domain are simulated). Adaptive domain is a pre-requisite for some of the ocean toolset features we will be adding. We'll add more details to this project to issue #286 (Adaptive Domain) once we move our priority after finishing the force field feature set. For now, we'll close this issue.

- Ryan

**Comment by rlguy** [comment]
Thanks for sharing, that's wonderful work! I've linked to this animation in the _Featured Artwork_ section of our latest developments notes here: https://flipfluids.com/weekly-development-notes-39-experimenting-and-testing/

I'll also post this to our social media on Monday or Tuesday, which seem to be more popular days for postings.

If you ever need to send us a message, you can also contact us at support@flipfluids.com.

\- Ryan
