### ISSUE TITLE
Fluid goes off

### ISSUE THREAD

**Issue by KIO04** [rlguy/Blender-FLIP-Fluids#513]
#### System Information

**Blender Version (including hash): 2.91
**FLIP Fluids Version: 1.09
**Operating System: Mac
**CPU: 2
**GFX:**
**RAM: 8

#### Describe the bug

Fluid does not interact with imported from GIS buildings (FLIP Fluid) Add-on. I want to fluid interact with buildings. Firstly, I baked with 100 resolution, than I decided to bake with 200 and 350 resolution, but still nothing. Images will show you my problem. Please help me, thanks in advance.

#### To Reproduce

Provide descriptive instructions for how to reproduce the issue or how to use your .blend file.

#### Expected Behaviour

I expected to fluid interact.

#### Actual Behaviour

It didn't interact.
<img width="1440" alt="Снимок экрана 2021-01-17 в 22 19 36" src="https://user-images.githubusercontent.com/77590794/104856727-0ce21980-591d-11eb-9666-0d4aafff0974.png">
<img width="1440" alt="Снимок экрана 2021-01-17 в 22 21 37" src="https://user-images.githubusercontent.com/77590794/104856729-110e3700-591d-11eb-8019-f9cf77e7fa6b.png">

**Comment by rlguy** [comment]
Hi KIO04,

Thanks for the report! Would be able to attach a .blend file that reproduces this issue? A .blend file will be required so that we can take a look at the object geometry. You may also send us the file to support@flipfluids.com.

This documentation topic may be relevant for the situation: [Manifold Meshes](https://github.com/rlguy/Blender-FLIP-Fluids/issues/513)

\- Ryan

**Comment by KIO04** [comment]
Hello, I sent.

**Comment by rlguy** [comment]
Thanks for the file! I have send a more detailed answer in the email message. The problem is that the mesh object contains [Non Manifold Geometry](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes) and this object will need to be repaired.
