### ISSUE TITLE
Friction does not appear to work as intended.

### ISSUE THREAD

**Issue by asullenwench** [rlguy/Blender-FLIP-Fluids#517]
#### System Information

**Blender Version (including hash): 2.92.0 beta 5804bf25bdfe**
**FLIP Fluids Version: 1.0.9a**
**Operating System: Windows 10**
**CPU: AMD Ryzen 9 5950X**
**GFX: Nvidia GeForce RTX 3090**
**RAM: 32GB**

#### Describe the bug

I've come across an issue where, even with friction setting 1.0 (I would interpret this to mean full inheritance of acceleration, but perhaps this is wrong), fluids appear to experience very low friction when the surface upon which they lie moves quickly beneath them.

#### To Reproduce

It happened in my full scene and was easy to reproduce in a test scene by just animating a fast-moving collider under a puddle.  Aggressive CFL and frame substeps don't seem to have helped.

#### Expected Behaviour

With a full 1.0 friction, when the rock makes any motion, I would have expected the fluid in contact to come along with it almost entirely if not entirely.

#### Actual Behaviour

The fluid only receives a small fraction of the rock's acceleration, and it appears to be worse the faster the collider is moving.

Blend file & cache (2.5 MB):
(url
[frictest3.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/5952541/frictest3.zip)
)

**Comment by rlguy** [comment]
Hi asullenwench,

Thanks for the report and .blend file! I am sorry to say that having the fluid stick completely to the object may not be possible in this simulator with this amount of rapid movement. The friction value will help fluids stick, but even at a maximum value, this option cannot guarantee that the fluid will not slide away from the contact point.

Getting fluids to stick to fast moving objects is a common problem in FLIP-based simulators and this issue can also be found in other similar simulation systems. A common trick we've seen in other simulation systems is to add a force field to help fluid stick to objects better. We have an example .blend file detailed [here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Example-Scene-Descriptions#surface_force_fluid_adhesionblend). 

However, due to the large acceleration impulses of the object's motion, I do not think that a force field would help very much in this situation.

Hope this info helps, and let me know if you have any questions.

\- Ryan
