### ISSUE TITLE
Compiling AddOn for free: libname_debug not defined

### ISSUE THREAD

**Issue by Sirom777** [rlguy/Blender-FLIP-Fluids#522]
Hi @rlguy 

yes, I know, I should buy the addon, but for now, I can't effort it, and I need the addon for a tiny simulation/artproject.
I am a freelance student and have no interest in making money with flip fluid.

I'd very appreciate if you could help me with my problem. I am still considering buying the full version asap.

After installing everything with mingw etcetc. installing the addon in blender, working with Flip Fluid (it is awesome), I clicked "bake". and after baking it shows the following error:
Error Baking Fluid Simulation
name 'libname_debug' is not defined. 

Is there a chance to fix this?

thanks for your help and time,

cheers,
Sirom

**Comment by rlguy** [comment]
Hi Sirom777,

I am sorry to say that we are unable to provide personalized support for building/compiling the FLIP Fluids addon. Due to the wide variety of system and software setups, troubleshooting development environments can be difficult. Full build/compile instructions can be found here for both the release and debug libraries of the addon: https://github.com/rlguy/Blender-FLIP-Fluids#building

I am not sure what would cause that error unless the source had been modified or is out of date with the current version. Looking at the source, [_libname_debug_ is defined here](https://github.com/rlguy/Blender-FLIP-Fluids/blob/master/src/engine/pyfluid/pyfluid.py#L75), and if it was not able to be defined, a _LibraryLoadError: Unable to recognize system: ..._ should have been triggered instead.

If unable to build the addon, you may want to use the pre-compiled demo version: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/FLIP-Fluids-Demo-Addon

And if it helps, the Blender Market has a few 25% off sales during the year. Their Spring Sale should be coming soon.

\- Ryan

**Comment by Sirom777** [comment]
Hi Ryan,

thanks for the fast and detailed answer. I ll try my best to set it (btw
its also a good learning for me to compile stuff, total beginner).
but thanks a lot for the info about the 25 %. this would help a lot. I hope
it is sooner than later, cause I d have a deadline 17.03. for a small
artproject
for my university, and I d like to create something with FLIP Fluid.

if there d be any chance, that you could provide me already the 25 %
discount, I d be more than thankful, but I d also understand if not. In
that case I d hope, "Spring" is sooner than later for Blender Market.


Thanks again for this nice addon.

Greetz,

Sirom

Am Mo., 8. März 2021 um 20:29 Uhr schrieb Ryan Guy <notifications@github.com

**Comment by rlguy** [comment]
> if there d be any chance, that you could provide me already the 25 %
discount, I d be more than thankful, but I d also understand if not. In
that case I d hope, "Spring" is sooner than later for Blender Market.

Send us a message through our [Blender Market page](https://blendermarket.com/products/flipfluids) and I'll see what we can do.
