### ISSUE TITLE
bpy.ops.flip_fluid_operators.copy_cache()  Error copying cache directory: name 'shutil' is not defined

### ISSUE THREAD

**Issue by kuzynsyna** [rlguy/Blender-FLIP-Fluids#524]
bpy.ops.flip_fluid_operators.copy_cache() not working in FLIP Fluids Version 1.0.9a
return error 
Error copying cache directory: name 'shutil' is not defined

**Comment by rlguy** [comment]
Hi, thanks for the report! The Copy Cache operators (and Move/Rename) were deprecated in FLIP Fluids version 1.0.8 and were removed from the UI in the FLIP Fluid Cache panel. These were removed because a potential Blender crash while using these operators could result in the cache becoming corrupted. To copy a cache, it would be best to do so using your OS filesystem which is capable of handling failures without corruption.

For the next version I have removed these operators from being registered in Blender so they cannot be found through the F3 menu or used in scripting.
