### ISSUE TITLE
Python 3.9 Error: AttributeError: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by Rainerr123** [rlguy/Blender-FLIP-Fluids#525]
![image](https://user-images.githubusercontent.com/57333628/112918399-5a59de80-9137-11eb-9ea1-e6be5d212f4e.png)

basic scene with domain and inflow object blender version 2.92.0

logs: https://pastebin.com/kGa5gaw2

**Comment by rlguy** [comment]
Hi Rainerr123,

This error is caused by a difference between Python versions. Normally Blender 2.92 officially distributes with Python 3.7, but some Linux distributions create their own versions with Python 3,9.

Blender will soon be updating to Python 3.9 in future versions and we have also recently updated our addon to be compatible with Python 3.9. This update will be available in the next version release which is FLIP Fluids 1.0.9b (April 6th, 2021).

Until then, there are two solutions to this error:
1. Use the latest FLIP Fluids experimental build: [Details here](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Experimental-Builds)
2. Or replace the following file on your system with the attached file (unzip to get trianglemesh.py):

```/home/rainer/.config/blender/2.92/scripts/addons/flip_fluids_addon/pyfluid/trianglemesh.py```

[trianglemesh.py.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/6225629/trianglemesh.py.zip)

Hope this helps!

\- Ryan

**Comment by Rainerr123** [comment]
amazing worked, thanks for the help :)
