### ISSUE TITLE
Baking Error PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by zbob90** [rlguy/Blender-FLIP-Fluids#529]
#### System Information

Blender Version: 2.92
FLIP Fluids Version:1.0.9b
Operating System: Windows 10
CPU: Intel core i7- 8657U
GFX: Intel R UHD Graphics 620
RAM: 16 GB

#### Describe the bug

 I bake the scene and around 10% through an error pops up. I've updated Blender and my graphics drivers but this still happens on any scene.  

#### To Reproduce

[flipFluid.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/6288044/flipFluid.zip)

#### Expected Behaviour

A description of what you expected to happen.

#### Actual Behaviour

A description of what actually happened.

#### Screenshots

![IMG-8580](https://user-images.githubusercontent.com/82236930/114231017-df1ed680-9947-11eb-9992-1ff83f48fd20.jpg)

**Comment by rlguy** [comment]
Hi zbob90,
Thanks for sending a report! This error means that there is a file in use by another process and is unable to be deleted by the Windows OS. Here are a few things to try:

- The first thing to check is to make sure that your simulation cache directory is not located on a network drive, or a synced location such as Dropbox or Google Drive. These types of file locations can cause conflicts with how the addon operates due to accessing these files while they are being modified.
- Try setting the cache directory to a new location in the FLIP Fluids Cache panel and baking again.
- Try rebooting your system to ensure the file is no longer in use

Hope this info helps! Let us know if any of these tips work for you or if you have any more info on the issue.

\- Ryan

**Comment by rlguy** [comment]
Since we have not heard back on this issue, we have added a workaround to bypass this error. The file being deleted is just a small temporary file and it is not critical that it is not deleted, so the addon will ignore the error and continue running as a workaround. This fix will be available in Experimental Version 9.0.9.20 (05-may-2021) or in stable versions later than 1.0.9b.

If you have any information on this issue, or are experiencing issues in a future versions, please let us know and we can re-open this issue thread.
