### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#533]
#### System Information

**Blender Version (including hash):** 2.93.0 Beta 3735986e8759
**FLIP Fluids Version:** 9.0.9.19
**Operating System:** windows 10 64 bit
**CPU:** AMD a8 5600k
**GFX:** -
**RAM:** 16 GB

#### Describe the bug

The text does not fit completely:
![01](https://user-images.githubusercontent.com/7983249/116783367-096f3a00-aa97-11eb-9f92-904bbff561c4.jpg)
![02](https://user-images.githubusercontent.com/7983249/116783371-0c6a2a80-aa97-11eb-8180-f88feb181161.jpg)

Colon is missing:
![03](https://user-images.githubusercontent.com/7983249/116783389-260b7200-aa97-11eb-85d1-9aac8b4a385c.jpg)

There is not enough space for the label. You can split row in half:
![04](https://user-images.githubusercontent.com/7983249/116783417-5226f300-aa97-11eb-8cb2-5b4e99f1be21.jpg)
![05](https://user-images.githubusercontent.com/7983249/116783420-55ba7a00-aa97-11eb-97d5-9a44d4267669.jpg)

Statistics are printed even if the frame is not baked. You can print zeros instead of real statistics values. Or write a `-` or `?` symbol:
![06](https://user-images.githubusercontent.com/7983249/116783498-aaf68b80-aa97-11eb-85dd-982a853a6dc6.jpg)

**Comment by rlguy** [comment]
Thanks for the report and screenshots! These have been fixed except for the last statistics issue.

The statistics will display the last successfully loaded statistics. This is to prevent the addon from loading the statistics file on every frame change to check which statistics labels to display. This is a design issue in the addon that can be fixed in future development.
