### ISSUE TITLE
Alembic export in 2.92/2.93

### ISSUE THREAD

**Issue by jcnwholland** [rlguy/Blender-FLIP-Fluids#542]
#### System Information

**Blender Version (including hash):version: 2.92.0, branch: master, commit date: 2021-02-24 16:25, hash: 02948a2cab44, type: Release
**FLIP Fluids Version: flip_fluids_addon (version: (9, 0, 9),
**Operating System: windows 10, up to date
**CPU: amd ryzen 7 5800
**GFX: nvidia RTX 3060 
**RAM: 16 GB

Hi, I did an extensive search and investigation on the feature to export the fluid mesh to animated alembic, however I can not get it to work. 
Opening the file in other programs ( embergen, side fx geometry viewer, houdini apprentice) results in a single frame mesh, not animated, while the file is 2 gb in size, and does seem to contain the animation data, but not the base geometry to apply it to.

- With e.g. other sims run in blender ( e.g.) cloth, i'm able to export a animated mesh in alembic, 
- I;ve applied the modifier trick ect 

I've read things about errors in the blender export and that they were/are working on it? But cannot find a definite answer.  Can anyone help with this?

**Comment by rlguy** [comment]
Hi, thanks for the report! However, I think the best route to getting an answer or a fix to this issue is to report this as a bug to the Blender developers ([Blender Bug Report Process](https://wiki.blender.org/wiki/Process/Bug_Reports)).

We do not have control over how Blender exports geometry to an Alembic file. This part of Blender is maintained by the Blender developers. We can only test and report issues related to Alembic files not importing correctly back into Blender. Related topic: [Alembic Support: Alembic export for use in other software](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Alembic-Export-Support#alembic-export-for-use-in-other-software).

Here are some suggestions for how to report this issue to the Blender developers.

- Attach a small .abc file that reproduces the issue. Such as a low detail simulation for just 10 frames.
- Attach a small .abc file that works, such as a cloth simulation.
- If you can export to Alembic using an [older version of Blender](https://www.blender.org/download/previous-versions/) and show that this works correctly, the issue may get more attention and may be labelled as a 'regression' bug.

If you do end up reporting this to the Blender developers, please do share a link to the issue and I will follow the bug report process and can add any input if needed.

For now, I will need to close this issue. Hope this info helps!
