### ISSUE TITLE
I am finding trouble compiling the addon.

### ISSUE THREAD

**Issue by Yehonam** [rlguy/Blender-FLIP-Fluids#544]
Hi Mr. Ryan Guy,
When I am trying to compile and build the addon, I get error messages in command prompt stating that it cannot find the cmake.txt file so I move it under the Blender-FLIP-Fluids-master folder which has been unzipped, but then why I do try it reads the CmakeLists.txt file but then gives me error messages in the following pictures.
![Command Prompt 28_07_2021 21_59_32](https://user-images.githubusercontent.com/88112545/127402615-fa2fde39-6415-4d92-8c6f-af167880058a.png)
![Command Prompt 28_07_2021 21_59_40](https://user-images.githubusercontent.com/88112545/127402623-9b8a809c-5959-469b-9892-1cf76a8e75f0.png)
![Command Prompt 28_07_2021 21_59_50](https://user-images.githubusercontent.com/88112545/127402624-27f3b7ed-4f00-4023-b7ae-88a2ae580fd7.png)
![Flip Fluids compiling error 01](https://user-images.githubusercontent.com/88112545/127402629-576d57ae-0591-4fc3-ab5c-5b33c5fc3635.png)

**Comment by Yehonam** [comment]
Please reply as soon as possible.

**Comment by rlguy** [comment]
Hi,

This issue tracker is only meant for issues related to the [Blender Market version of the FLIP Fluids addon](https://blendermarket.com/products/flipfluids). We are unable to provide support/troubleshooting here (or through the Blender Market) for building/compiling the GitHub version of the addon due to the difficulty in troubleshooting a wide variety of users' systems and set ups.

We include complete instructions for building the FLIP Fluids addon in the GitHub readme here, however some programming experience may be necessary: https://github.com/rlguy/Blender-FLIP-Fluids#building

> To build the FLIP Fluids addon, some programming experience or prior experience building C/C++ applications is recommended. The basics of navigation and executing commands using the command line is also recommended.

Tips: I would first try verifying that the missing files exist and that everything is in the correct location. Something to try would be to delete all of the source and try again according to the readme build instructions.

**Comment by Yehonam** [comment]
Ok thanks 😀
