### ISSUE TITLE
Noise or Turbulance Force?

### ISSUE THREAD

**Issue by enzyme69** [rlguy/Blender-FLIP-Fluids#548]
<img width="1226" alt="Screen Shot 2021-08-05 at 10 12 28 pm" src="https://user-images.githubusercontent.com/3952687/128347901-98af590f-684e-485c-bf9f-f3f6614a2996.png">

I have this animated head, with blendshapes, and I am using this as Surface Force Field, after some playing around with the parameters, I get to the one where fluid sticks to the head quite faithfully. 

However, I think the fluid particles are sticking too much and so the fluid does not feel realistic. I wish that there might be a way to randomize, or influence the force a little bit more so the liquid would "escape" and be less perfect, and kind of acting a bit like sweat, but also getting push and pull.

Currently I am getting either fluid completely sticking, or half sticking to the floor and some stuck on the fluid, not much vector speed animation affecting the fluid.

I wonder if we will have turbulance force for this, or you have better idea to add randomization noise into the Surface Force so that it will act a little bit more interesting, juggling between surface, gravity, and turbulance noise?

**Comment by rlguy** [comment]
Hi, thanks for sending us a message! However, this issue tracker is only meant for bugs or issue reports and feature requests or questions are not accepted on the tracker. See this document for more information and for proper channels to contact us about feature requests: [Guidelines for Feature Requests](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Feature-Requests).

A turbulence fore field feature is partially completed ([More Info in dev notes #43](https://flipfluids.com/weekly-development-notes-43-turbulence-with-curl-noise/)), but at the moment it is not being actively worked on due to other development priorities taking its place. A turbulence force field would be useful for many applications, one of them being to add some variation to other force fields.
