### ISSUE TITLE
Baking crash (Out of Memory)

### ISSUE THREAD

**Issue by KobyDeuel** [rlguy/Blender-FLIP-Fluids#549]
I am trying to bake a sim, but it keeps crashing. I have a semi-complex scene with a bottle breaking in slow-mo with fluid in it. I don't want to wait 10+ hours so I let it bake run overnight. Every time I have done this, I wake up to blender crashed. I have tried lowering the res to the lowest I could without having fluid leak out, 250, but it keeps crashing. When I start the bake it seems to be doing fine and I have watched it for an hour at res 300+. It is only when I leave it for several hours. I also have 32Gb of ram which is not a lot but also not a small amount. Any ideas why it is crashing?

**Comment by rlguy** [comment]
Hi, thanks for the report!

Would you be able to try [baking the simulation from the command line](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Baking-from-the-Command-Line) to capture any error messages that may be displayed before a crash? 

And please also include your FLIP Fluids and Blender version info and system information ([Guidelines for Reporting Bugs and Issues](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues)).

Depending on the result of running the simulation from the command line, we may also require a .blend file that reproduces the issue in order to investigate.

**Comment by KobyDeuel** [comment]
I will give it a shot. 

Blender Version: Blender 2.93.2
FLIP Fluids Version: 1.0.9b
Operating System: Windows 11, This might be why
CPU: Ryzen 5 2600 3.40GHz
GPU: RTZ 3080, 10GB
RAM: 32GB

**Comment by KobyDeuel** [comment]
It still crashes when running from CMD. It closes the window so I'm not sure how to record the error

**Comment by KobyDeuel** [comment]
I also tried a low resolution and it still crashes a lot sooner than it does in normal blender

**Comment by rlguy** [comment]
Thanks for the update! That is an interesting result. The CMD window is separate from Blender and should not close after Blender crashes. This may indicate that the problem is outside of Blender and could be something that is shutting down the process. It could also be possible that this is an issue related to Windows 11.

Are you able to locate and upload any of [Blender's crash logs](https://docs.blender.org/manual/en/latest/troubleshooting/crash.html#crash-log)? These won't contain errors related to the simulator, but may contain info on what is causing Blender to close.

If you are able to attach the .blend file, or send to support@flipfluids.com, I would be glad to check it out and see if this issue can be reproduced on our systems.

Let me know if you have any questions or find any more information.

**Comment by KobyDeuel** [comment]
Thanks. I’ll send it over.

**Comment by rlguy** [comment]
Thanks for sending the .blend file for testing!

The issue was caused by an object that was much larger than the domain being set as an obstacle, which resulting in crashes due to requiring too much memory.

Relevant topic: [Does my obstacle object need to be completely contained by the domain?](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Obstacle-Object-Settings#does-my-obstacle-object-need-to-be-completely-contained-by-the-domain)

> **Does my obstacle object need to be completely contained by the domain?**
> No, it is okay for your object to be larger than the domain. However, we do not recommend the object to be very large compared to the domain size. Objects much larger than the domain will require more RAM and can slow down computation or you may even run out of memory. For very large objects, you may want to create smaller trimmed down proxy object for use in the simulator.
