### ISSUE TITLE
Error when baking using curve force field

### ISSUE THREAD

**Issue by SohailNordin** [rlguy/Blender-FLIP-Fluids#550]
#### System Information

**Blender Version (including hash): 2.93.3**
**FLIP Fluids Version: 0.0.9**
**Operating System: Windows**
**CPU: Intel core i7-10750H**
**GFX: Nvidia Geforce GTX 1660 Ti**
**RAM: 32GB**

#### Describe the bug

Error message appears when trying to bake a curve force field. The curve is from the "Add curve : Extra objects" add-on. 

#### To Reproduce

Add an Archimedean curve spiral and set it to force field.

#### Expected Behaviour

The fluid follows the curve

#### Actual Behaviour

Error message pops up and the bake is stuck at "Cancelling... Safe to quit Blender".

#### Screenshots

![Screenshot (101)](https://user-images.githubusercontent.com/89077784/129716733-93bf6c3f-2c1a-4452-a7f5-43a0baf8f77e.png)

Here is the file : https://drive.google.com/file/d/10lZzyx8psbADO4PqFjNc36FKIGEKpET1/view?usp=sharing

**Comment by rlguy** [comment]
Hi, thank you for the bug report!

This error is caused by a bug in the FLIP Fluids addon where not all of Blender curve types are supported.

This bug has been fixed and will be available in the next versions of the addon to be released on August 20th (v0.1.0 demo, v1.1.0 Stable).
### Workaround

Until the next release, a workaround is to convert the curve spline type to 'Bezier' in Edit Mode:

![set_spline_type](https://user-images.githubusercontent.com/4285191/129778858-51c7f200-a800-4b04-ac6d-938d82fdc3a4.jpg)

**Comment by SohailNordin** [comment]
Ahh alright, thank you!
