### ISSUE TITLE
Jittery playback when rendering with two Blender Instances

### ISSUE THREAD

**Issue by baronlanteigne** [rlguy/Blender-FLIP-Fluids#559]
Both instances used the same .blend file which refers to the same Fluid Cache Directory.
Simulated mesh loads fine in the viewport but it seems different data was used by the two blender instances while rendering.
Blender kept crashing during the process too but that might not be related at all.
Using Blender 3.0.0 Beta.

**Comment by rlguy** [comment]
Thanks for the report!

For most of the animations that I render out, I use multiple instances of Blender for rendering, but I have not noticed this type of issue so far.

Would you be able to provide the following information and files so that I can investigate this issue:

- An animation or images showing the type of jittering playback.
- Does the issue still happen if rendering through [command line instances](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Rendering-from-the-Command-Line)?
- [System and FLIP Fluids addon version information](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues#be-complete).
- A .blend file that can reproduce the issue and detailed instructions for how to reproduce the issue.

Feel free to send any files to support@flipfluids.com if needed.

**Comment by johannbl** [comment]
I have yet to try the command line rendering. I'm probably missing out. I'll give it a shot. I have a feeling I've been missing out.

Here is a preview of the issue:
https://imgur.com/a/1gTYS8U
First I manually scrub through some frames where the issue happens, you see the same sim data being used for different frames. Then I let a short sequence play twice, you can see the jitter and then the end is smooth.

I know it's not blender that did not render the correct frames because in other parts of the render with other objects, we can see the liquid being jittery but the camera motion is smooth.

I had several crashes while rendering, sometimes one instance would crash way before the other. So I suspect the parts where the simulation is smooth is due to when only one instance was rendering.

Here is more details about the machine:

Blender: Blender 3.0.0 beta 31-OCT-2021, a06abbac9f2
FLIP Fluid: 1.1.0 (Stable 20-AUG-2021)
OS: Windows 10
CPU: AMD 3970x
GPU0: 3080
GPU1: 3080
RAM: 128GB

**Comment by rlguy** [comment]
Thanks for the update! It's possible that this issue could be related to Blender 3.0 compatibility.

Unfortunately, builds of Blender 3.0 since early October are no longer compatible with FLIP Fluids 1.1.0. There have been changes in Blender 3.0 that cause serious bugs when using FLIP Fluids 1.1.0. These bugs can cause incorrect initialization of the fluid_surface, which may explain incorrect loading behaviour, as well as side-effects that can cause corrupted data in the .blend file.

Some of the side-effects of these bugs may not be repairable in the .blend file. Feel free to attach or send the .blend file and I would be glad to take a look and see if there are any problems or if it can be repaired.

Recent builds of Blender 3.0 should be used with the latest [FLIP Fluids Experimental Builds](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Experimental-Builds). Issues related to Blender 3.0 can be tracked in issue #535.

---

> I have yet to try the command line rendering. I'm probably missing out.

Tip: Command line rendering is the most stable method of rendering in Blender. On Windows, the 'FLIP Fluids' sidebar menu contains some command line operators for automatically launching a render: [Helper Menu Settings > Command Line Tools](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Helper-Menu-Settings#command-line-tools).

**Comment by johannbl** [comment]
Thank you so much. I will test using the latest build and command line. If the issue remains, I'll try to see if I can reproduce with a different blend or clean up my blend file.

**Comment by rlguy** [comment]
Thanks for the update! Just noticed the edit. If I recall correctly, I don't think there are commands to assign a specific GPU, so saving the preferences before launch would be the best route. Perhaps we may find a scripting solution for this to add to the command line menu in future development.
