### ISSUE TITLE
Mesh Generation Bug when 'Meshing Against Obstacles' option is disabled

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#567]
#### System Information

**Blender Version:** 2.93.6, master, 2021-11-16 14:54, c842a90e2fa1
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.2.0 Stable 25-NOV-2021)
**OS:** Windows-10-10.0.19041-SP0
**GPU:** -
**CPU:** AMD A8-5600K APU with Radeon(tm) HD Graphics   
**RAM:** 16 GB

#### Describe the bug

A fluid mesh is created within the walls of the domain.

#### To Reproduce

Bake this scene:
[mesh_bug.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/7592616/mesh_bug.zip)

#### Screenshots

![01](https://user-images.githubusercontent.com/7983249/143172591-26540965-ca8c-4609-8bba-84266df4c7e6.jpg)
![02](https://user-images.githubusercontent.com/7983249/143172599-e027960e-ca4a-4627-80cf-aa8e104e47bf.jpg)
![03](https://user-images.githubusercontent.com/7983249/143172718-44072b04-228a-4e41-9179-f8bf8e149779.jpg)

**Comment by rlguy** [comment]
Thanks for the report! I am able to reproduce this issue. This bug will happen if the 'Meshing Against Obstacles' option is disabled.

The cause of the bug is due to a recent change in the simulator. I had overlooked how this change would affect the mesh results when this option was disabled. This has been fixed and will be available in the next experimental version (v9.2.2, release TBD).

![image](https://user-images.githubusercontent.com/4285191/143177905-78d5f18c-876f-4790-8717-6852fa8fd1b6.png)
