### ISSUE TITLE
crash when render eevee animation 

### ISSUE THREAD

**Issue by milkinhale** [rlguy/Blender-FLIP-Fluids#604]
#### System Information

**Blender Version:** 3.4.1, blender-v3.4-release, 2022-12-19 17:00, 55485cb379f7
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.2.0 GitHub Release 26-NOV-2021)
**OS:** Windows-10-10.0.19045-SP0
**GPU:** AMD Radeon RX 6700 XT ATI Technologies Inc. 4.5.0 Core Profile Context 22.11.2.221130
**CPU:** Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
**RAM:** 48GB

#### Describe the bug

I've baked fluids using Flip Fluids, but when I try to render eevee animation, blender crashes. If I disable the fluid surface mesh, it renders without any issue. Only if I able the fluid surface, blender crash.

#### To Reproduce

You just have to render animation (Ctrl + F12) to crash the blend file. 
If you disable the fluid_surface mesh, then it renders without any issue.
You can download my blend file to reproduce the issue.
(It contains NSFW contents.)
https://www.mediafire.com/file/xjfb7ppofs8zwbz/untitled3.blend/file

#### Expected Behaviour

I'm expecting it not to crash when I render eevee animation.

#### Actual Behaviour

blender.exe crash without any warning. 

#### Screenshots
If I disable the "fluid_surface" mesh, it renders without any issue.
Only if I turn on the "fluid_surface" mesh, blender crashes when I start render eevee animation.

![image](https://user-images.githubusercontent.com/62606734/212540024-595ca013-d6b4-4aeb-a17f-be9b032b8a82.png)

https://www.mediafire.com/file/xjfb7ppofs8zwbz/untitled3.blend/file

**Comment by rlguy** [comment]
Thanks for the report! 

I am sorry to say that we are unable to test NSFW scenes (thanks for the warning). We are only able to test scenes that would be considered appropriate when viewed in a public office setting. If you are able to recreate the issue in a SFW scene, we could take a look for any problems in the simulator.

However, I would suggest to first update the FLIP Fluids addon to the most recent GitHub release version which is 1.6.0 and test again. FLIP Fluids 1.2.0 is only compatible with Blender versions up to Blender 3.0 and will result in issues when using in Blender 3.4.

Please let us know if this issue is still present in FLIP Fluids 1.6.0 or later or if you find any more information about the issue.

**Comment by rlguy** [comment]
Closing this issue thread due to inactivity. Let us know if running FLIP Fluids 1.6.0 or later results in any changes to the issue and we can re-open the issue.
