### ISSUE TITLE
more affordability

### ISSUE THREAD

**Issue by MrMage750** [rlguy/Blender-FLIP-Fluids#618]
let me ask, first and foremost, who on the flipfluids team thought it was a good idea to charge a whopping 76 USD for ONE addon, that likely costed no more than 1 grand to produce??? fr, anyone who isn't a conglomerate or some other rich and haughty person would be out of their mind to throw exorbitant amounts of money at addons like these when there's other, much more affordable options that can get the job done well enough, minus the fancy bells and whistles this addon has, if you ask me, 20-30 USD would be a fair price for what you get, because there is no justification to gouge this addon's price when there are free addons that can do about the same things

**Comment by rlguy** [comment]
Hi, I think you may not understand the amount of work and resources required to fund and develop this product. If you can find better addons or tools that do the same things and are a better value for you, use these tools instead.

This project is also open source and we provide the source code and instructions on how to build the FLIP Fluids addon for free here: https://github.com/rlguy/Blender-FLIP-Fluids

This issue tracker is for bug related to the FLIP Fluids addon rather than discussions like these, so I will be closing the issue.
