### ISSUE TITLE
Strange fog

### ISSUE THREAD

**Issue by Giardia2** [rlguy/Blender-FLIP-Fluids#638]
Hello I got in to thus strange problem. Simulation produce this strange fog and it doesn't produce any bobbles or foam on the water.
what can I do about it?
<img width="663" alt="Snímek obrazovky 2024-06-23 v 10 24 35" src="https://github.com/rlguy/Blender-FLIP-Fluids/assets/173599248/817534b5-2bf5-4d05-be85-03b5067285d4">

**Comment by rlguy** [comment]
Hi, it looks like this scene is currently being rendered in EEVEE which can have these types of volumetric can whitewater rendering limitations by default. The Cycles renderer can be a better choice with default settings.

The fog can be caused by an EEVEE limitation where volumes are rendered as bounding boxes: https://docs.blender.org/manual/en/latest/render/eevee/limitations.html#materials

> **Volume Objects**
> Object volume shaders will affect the whole bounding box of the object. The shape of the volume must be adjusted using procedural texturing inside the shader.

By default, the whitewater particles are rendered using Point Cloud objects, which are not currently supported by EEVEE. More information can be found in this topic (in EEVEE Support Notes): https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Display-Settings#fluid-particle-display-settings

> **EEVEE Support Notes:** The EEVEE render engine does not current support rendering Point Cloud objects. For rendering particles in EEVEE, use the Enable Particle Instancing option to convert the whitewater meshes to instanced icospheres. However, rendering a large amount of particles in EEVEE can be very slow and use more resources compared to the Cycles render engine. 

For future scene troubleshooting help, please contact us through our scene troubleshooting support channels rather than this GitHub issue tracker: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines#scene-troubleshooting
